{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1558.0 (25.03)+75b5f06a991f8f8a8a4d6b6fcd0f66e1ec2d6fdc"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"func_GuestCounts\",\"Query1\",\"Query2\",\"VIP_WonderPassPlaysByCategory\",\"VIP_Parking\",\"Family Pack\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "func_GuestCounts",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = () => let",
          "    Source = Sql.Databases(\"gvbidbserver.database.windows.net,1433\"),",
          "    GVPBIDB = Source{[Name=\"GVPBIDB\"]}[Data],",
          "    dbo_GuestCounts = GVPBIDB{[Schema=\"dbo\",Item=\"GuestCounts\"]}[Data]",
          "in",
          "    dbo_GuestCounts",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "a91ea707-cd7c-479b-b889-52b47b6358c9",
        "queryGroup": "func_GuestCounts"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "func_GuestCounts"
      }
    ],
    "relationships": [
      {
        "name": "9edbd83e-b22b-4066-a54a-df7d48a3b345",
        "fromColumn": "VW_VIPActivationDataset_DOB",
        "fromTable": "Query1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_457552a2-3594-43b7-be53-c6fd1b316588"
      },
      {
        "name": "cf4996d1-a5b5-41c8-ad03-d76300b25396",
        "fromColumn": "Activated_at",
        "fromTable": "Query1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_13c1f7c3-4b1d-4af5-b5be-c53dea229164"
      },
      {
        "name": "1281f319-69c1-46dc-9185-1107cb1662a4",
        "fromColumn": "SaleDate",
        "fromTable": "Query1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6560ee15-3699-48a4-b15e-ec59a82c404c"
      },
      {
        "name": "0d0ec51b-86b6-441f-b0e3-62b83c055b85",
        "fromColumn": "Activated_at",
        "fromTable": "Query2",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_59a958fb-ab4d-4811-b12b-6b0ebd526453"
      },
      {
        "name": "8792d705-bff3-4c54-b72f-5bb549180847",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Season+Pack",
        "fromTable": "Query1",
        "toCardinality": "many",
        "toColumn": "Season+Pack",
        "toTable": "Query2"
      },
      {
        "name": "7f0fe410-4544-4181-b96b-2530c3a012f7",
        "fromColumn": "VW_VIPActivationDataset_DOB",
        "fromTable": "Distinct packs",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1a28d957-6c5d-4faa-90d9-a455f0254878"
      },
      {
        "name": "0e4776e2-9df6-44bc-b11c-8bea94fada94",
        "fromColumn": "Activated_at",
        "fromTable": "Distinct packs",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e0611511-ec1c-4e40-85a6-01bf0bb1ee60"
      },
      {
        "name": "de01d3dd-5dd8-4d88-9095-a0063fb7f9a4",
        "fromColumn": "SaleDate",
        "fromTable": "Distinct packs",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7bc5946e-77c0-415b-b60d-baa43e5eb460"
      },
      {
        "name": "dffd0da7-1b67-44a9-a919-7ea45e8ffbb7",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Season+Pack",
        "fromTable": "Query2",
        "toCardinality": "many",
        "toColumn": "Season+Pack",
        "toTable": "Distinct packs"
      },
      {
        "name": "83cfe3bf-6936-4221-b678-25217bd5f172",
        "fromColumn": "Op_date",
        "fromTable": "VIP_Parking",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3b61af33-bad5-4f12-8b5d-d0f12bdd4798"
      },
      {
        "name": "c931eec2-de8a-47b3-837c-8bcd85373d13",
        "fromColumn": "Activated_On",
        "fromTable": "Family Pack",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7a13ada1-fa66-4deb-ba1a-4423b16aeac0"
      },
      {
        "name": "31da555a-5de5-4c06-9dee-c0a672c38c97",
        "fromColumn": "Activated_On",
        "fromTable": "Distinct family packs",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2eb98c04-eb59-4d06-aa8b-237a6377b0df"
      },
      {
        "name": "2142ebc5-1388-478e-af30-8c7de30f6a00",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Season + Pack No",
        "fromTable": "Distinct family packs",
        "toCardinality": "many",
        "toColumn": "Season + Pack No",
        "toTable": "Family Pack"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_97050f7e-6683-4083-82fd-a53961a7ba79",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "60b05770-3ee8-423e-b97f-cde1dda845d3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9bcd5802-c8cd-4856-b7a6-fcd3381db692",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "34ab3d01-503d-4c05-aa5e-8256ed3547ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b19bae1a-0e37-4927-96b2-b4d0a5e635a8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bf8d944f-5cf1-4243-87c3-e9d22e36da26",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba8ad2f0-7396-4666-b670-5cbdeec60e39",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "820cf1fb-ce57-4344-87bf-f64dbfe4fb6b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0568743e-eea4-4a13-b039-5a291e577bb5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a3554bf1-60c1-4740-8623-30c57855e238",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3f5258c1-e468-4664-81a6-f70cd52588ae",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3edfb7cf-e055-4884-baa1-e88833555117",
                "ordinal": 3
              }
            ],
            "lineageTag": "92bd5bdd-5c2a-495f-8420-b405c7410141"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e3710b71-e40d-4a94-9fed-77c6e807dc36",
        "partitions": [
          {
            "name": "DateTableTemplate_97050f7e-6683-4083-82fd-a53961a7ba79-9cf1f88d-4152-4d07-9904-cf2733552d03",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Query1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Season_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2be6f6e-cb06-4cb8-9418-79f6bf976016",
            "sourceColumn": "Season_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Season+Pack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3cce700-4356-4470-9b72-12d7ec8372f8",
            "sourceColumn": "Season+Pack",
            "summarizeBy": "none"
          },
          {
            "name": "Virgin_Pack_No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25be37aa-80a9-45eb-87ae-f791ac987583",
            "sourceColumn": "Virgin_Pack_No",
            "summarizeBy": "none"
          },
          {
            "name": "Virgin_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b9000a0-380f-44d0-9a4e-c83ea8c32e6d",
            "sourceColumn": "Virgin_Email",
            "summarizeBy": "none"
          },
          {
            "name": "VW_VIP_ActivationDataset_Pack_No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1b1abb57-bc33-4969-ac14-02623d2e31e8",
            "sourceColumn": "VW_VIP_ActivationDataset_Pack_No",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63ff6679-8674-4292-825e-7d800324985c",
            "sourceColumn": "VW_VIPActivationDataset_Category",
            "summarizeBy": "none"
          },
          {
            "name": "VW_VIPActivationDataset_Sale_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0617e89-8d73-4115-82ae-d3337e033bf7",
            "sourceColumn": "VW_VIPActivationDataset_Sale_Type",
            "summarizeBy": "none"
          },
          {
            "name": "VW_VIPActivationDataset_DOB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b5b334ea-3eb7-42a7-a8c3-903ac44735fd",
            "sourceColumn": "VW_VIPActivationDataset_DOB",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_457552a2-3594-43b7-be53-c6fd1b316588"
                },
                "isDefault": true,
                "relationship": "9edbd83e-b22b-4066-a54a-df7d48a3b345"
              }
            ]
          },
          {
            "name": "VW_VIPActivationDataset_Nationality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30f8fd84-257e-4e51-b9ae-30d81789f094",
            "sourceColumn": "VW_VIPActivationDataset_Nationality",
            "summarizeBy": "none"
          },
          {
            "name": "VW_VIPActivationDataset_Entry_Tickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b3b99387-9ee8-46d4-909a-3ff585d69063",
            "sourceColumn": "VW_VIPActivationDataset_Entry_Tickets",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_Entry_Tickets_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5855493e-1e7a-4318-9cad-ef4c58d36bfa",
            "sourceColumn": "VW_VIPActivationDataset_Entry_Tickets_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_WonderPass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd4f9079-9d38-48a4-8e86-ef0ebbe31ff5",
            "sourceColumn": "VW_VIPActivationDataset_WonderPass",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_WonderPass_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e0517736-c7fb-431b-8609-44a8606b0c5d",
            "sourceColumn": "VW_VIPActivationDataset_WonderPass_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_Parking_Voucher",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b80b7e7f-1aff-4366-ad71-6ba5355dcec5",
            "sourceColumn": "VW_VIPActivationDataset_Parking_Voucher",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_Parking_Voucher_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2eaa1738-993c-4ad0-bdb9-092d51d3668c",
            "sourceColumn": "VW_VIPActivationDataset_Parking_Voucher_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_Auditorium",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "adb97905-09b1-4646-8754-fea61c305cc9",
            "sourceColumn": "VW_VIPActivationDataset_Auditorium",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_Auditorium_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49d1bfaa-8f95-43fc-8c4c-8e5edc8fc6ae",
            "sourceColumn": "VW_VIPActivationDataset_Auditorium_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_MirrorMaze",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0503f921-7d44-487b-934b-96e1a5b856a8",
            "sourceColumn": "VW_VIPActivationDataset_MirrorMaze",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIPActivationDataset_MirrorMaze_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f2fdcdf-5b2a-4075-b352-d51d01cd3c75",
            "sourceColumn": "VW_VIPActivationDataset_MirrorMaze_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIP_ActivationDataset_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25d2918f-c10d-43ca-8039-bd55a622cdfb",
            "sourceColumn": "VW_VIP_ActivationDataset_Email",
            "summarizeBy": "none"
          },
          {
            "name": "VIP_Utilization_Sold_OnSite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f0ab508d-4974-431e-a5fc-c4725efa335a",
            "sourceColumn": "VIP_Utilization_Sold_OnSite",
            "summarizeBy": "none"
          },
          {
            "name": "Activated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "db20a625-7a01-4821-afb1-9962a8809bbb",
            "sourceColumn": "Activated",
            "summarizeBy": "sum"
          },
          {
            "name": "Sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee9ebf3f-0627-4edf-8032-76a323c55201",
            "sourceColumn": "Sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_Type_Final",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(AND(NOT(ISBLANK('Query1'[VW_VIPActivationDataset_Sale_Type])),'Query1'[VIP_Utilization_Sold_OnSite]),\"GV On Site\",'Query1'[VW_VIPActivationDataset_Sale_Type])",
            "isDataTypeInferred": true,
            "lineageTag": "0c01459b-7d63-4545-8ed9-905a00a07e9f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "IF(IF('Query1'[VW_VIPActivationDataset_DOB] < Date(Year(TODAY()),Month(today()),DAY(today())), DATEDIFF('Query1'[VW_VIPActivationDataset_DOB], Date(Year(TODAY()),Month(today()),DAY(today())), DAY) / 365.25, 0)>100,0,IF('Query1'[VW_VIPActivationDataset_DOB] < Date(Year(TODAY()),Month(today()),DAY(today())), DATEDIFF('Query1'[VW_VIPActivationDataset_DOB], Date(Year(TODAY()),Month(today()),DAY(today())), DAY) / 365.25, 0))",
            "isDataTypeInferred": true,
            "lineageTag": "ee742f76-5bd4-4a62-a8fc-0b880863a2ed",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Age_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "bla",
            "expression": "IF(AND('Query1'[Age]>=25,'Query1'[Age]<=39),\"25-39\",IF(AND('Query1'[Age]>=40,'Query1'[Age]<=59),\"40-59\",IF(AND('Query1'[Age]>=18,'Query1'[Age]<=24),\"18-24\",IF(AND('Query1'[Age]>=60,'Query1'[Age]<100),\"60 Plus\",\"Unkown\"))))",
            "isDataTypeInferred": true,
            "lineageTag": "b61a5e5b-e09c-463f-aeaa-fee2acc97c22",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "day_num_tag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9a2c63f0-f5d5-49b4-804a-6bb35cbd8eb3",
            "sourceColumn": "day_num_tag",
            "summarizeBy": "sum"
          },
          {
            "name": "Activated_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "58157aa5-594b-4bc7-9c09-200192b5751c",
            "sourceColumn": "Activated_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_13c1f7c3-4b1d-4af5-b5be-c53dea229164"
                },
                "isDefault": true,
                "relationship": "cf4996d1-a5b5-41c8-ad03-d76300b25396"
              }
            ]
          },
          {
            "name": "Entry_Tickets_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'Query1'[VW_VIPActivationDataset_Entry_Tickets]-'Query1'[VW_VIPActivationDataset_Entry_Tickets_Remaining]",
            "isDataTypeInferred": true,
            "lineageTag": "575f14e0-dcfa-449d-99b3-779f8024d868",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Wonderpass_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "'Query1'[Wonderpass]-'Query1'[VW_VIPActivationDataset_WonderPass_Remaining]",
            "isDataTypeInferred": true,
            "lineageTag": "1bcfe067-8651-4d98-b230-eb58eb8dd25b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Parking_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Query1'[VW_VIPActivationDataset_Parking_Voucher]-'Query1'[VW_VIPActivationDataset_Parking_Voucher_Remaining]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "92ce07b8-176a-4599-a828-a71fdb96dd68",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ripleys_Combo_Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Query1'[VW_VIPActivationDataset_MirrorMaze]+'Query1'[VW_VIPActivationDataset_Auditorium]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7c2893b5-4679-4b07-ae00-487e4690ec1a",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ripleys_Combo_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Query1'[Ripleys_Combo_Total]-'Query1'[VW_VIPActivationDataset_MirrorMaze_Remaining]-'Query1'[VW_VIPActivationDataset_Auditorium_Remaining]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "55cf4d4b-13f3-4ef7-b345-201e58380a14",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "SaleDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5490decf-6663-4bcf-be4d-00df0823a66e",
            "sourceColumn": "SaleDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6560ee15-3699-48a4-b15e-ec59a82c404c"
                },
                "isDefault": true,
                "relationship": "1281f319-69c1-46dc-9185-1107cb1662a4"
              }
            ]
          },
          {
            "name": "New Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "IF(CONTAINSSTRING([VW_VIPActivationDataset_Category],\"media\"),\"8. Media Pack\", ",
              "",
              "IF(CONTAINSSTRING([Sales_Type_Final],\"mini\"),\"7. Mini\", ",
              "IF(CONTAINSSTRING([Sales_Type_Final],\"comp\"),\"6. Complimentary\", ",
              "IF(CONTAINSSTRING([Sales_Type_Final],\"media\"),\"8. Media Pack\", ",
              "IF(CONTAINSSTRING([VW_VIPActivationDataset_Category],\"Private\"),\"1. Private\", ",
              "IF(CONTAINSSTRING([VW_VIPActivationDataset_Category],\"Diamond\"),\"2. Diamond\", ",
              "IF(CONTAINSSTRING([VW_VIPActivationDataset_Category],\"Platinum\"),\"3. Platinum\", ",
              "IF(CONTAINSSTRING([VW_VIPActivationDataset_Category],\"Gold\"),\"4. Gold\", ",
              "IF(CONTAINSSTRING([VW_VIPActivationDataset_Category],\"Silver\"),\"5. Silver\", ",
              "",
              "[VW_VIPActivationDataset_Category])))))))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "bb0b1a48-e13f-4cab-83d4-89c103c19451",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VIP_Utilization_Cabana_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d1737f8b-5497-4857-ba46-07c21f27af25",
            "sourceColumn": "VIP_Utilization_Cabana_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP_Utilization_Stunt_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27044f40-fb83-4bb8-a394-ec73c5eeebf0",
            "sourceColumn": "VIP_Utilization_Stunt_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Stunt Show",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "/* IF([Season_ID]=27,",
              "IF('Query1'[New Category]=\"1. Private\",6,",
              "IF([New Category]=\"2. Diamond\",4,",
              "IF([New Category]=\"3. Platinum\",2,",
              "IF([New Category]=\"4. Gold\",2,",
              "IF([New Category]=\"5. Silver\",2,",
              "IF([New Category]=\"6. Complimentary\",2,",
              "IF([New Category]=\"7. Media Pack\",BLANK(),",
              "IF([New Category]=\"8. Mini\",BLANK(),Blank()",
              ")))))))))*/",
              "var op = IF('Query1'[New Category]=\"1. Private\",6,",
              "IF([New Category]=\"2. Diamond\",4,",
              "IF([New Category]=\"3. Platinum\",2,",
              "IF([New Category]=\"4. Gold\",2,",
              "IF([New Category]=\"5. Silver\",2,",
              "IF([New Category]=\"6. Complimentary\",2,",
              "IF([New Category]=\"7. Media Pack\",BLANK(),",
              "IF([New Category]=\"8. Mini\",BLANK()",
              "))))))))",
              "",
              "RETURN",
              " //IF(Query1[Season_ID]=27, op,IF(Query1[Season_ID]=28,op,BLANK()))",
              " IF(OR(Query1[Season_ID]=27,Query1[Season_ID]=28),op,BLANK())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2daeaf5c-b020-409d-83ee-93f643ba9576",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Stunt Show Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF([Stunt Show]=BLANK(),Blank(), [Stunt Show]-[VIP_Utilization_Stunt_Remaining])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "bd36dc12-87e4-4867-9537-3be723d99a42",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cabana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF([Season_ID]<>27,Blank(),",
              "IF([New Category]=\"1. Private\",2,",
              "IF([New Category]=\"2. Diamond\",1,",
              "IF([New Category]=\"3. Platinum\",1,",
              "IF([New Category]=\"4. Gold\",1,",
              "IF([New Category]=\"5. Silver\",1,",
              "IF([New Category]=\"6. Complimentary\",1,",
              "IF([New Category]=\"7. Mini\",BLANK(),",
              "IF([New Category]=\"8. Media Packs\",BLANK()",
              ")))))))))"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a6f5d71b-2862-40a2-8b12-4f77be82dabc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cabana Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF([Cabana]=BLANK(),Blank(),[Cabana]-[VIP_Utilization_Cabana_Remaining])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3108a529-0941-4a31-aaac-efaba7856520",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Activation Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "var daydiff= ",
              "IF(Query1[Season_ID]=28,DATEDIFF(DATE(2023,10,19),[Activated_at],DAY),",
              "IF(Query1[Season_ID]=27,DATEDIFF(Date(2022,10,26),[Activated_at],Day),",
              "IF(Query1[Season_ID]=26,DATEDIFF(Date(2021,10,25),[Activated_at],Day),",
              "IF(Query1[Season_ID]=25,DATEDIFF(Date(2020,10,26),[Activated_at],Day)))))",
              "return ",
              "if (daydiff<0,\"1. Activated before season starts\",",
              " if(daydiff<30,\"2. Activated within first months\",",
              " if(daydiff<60,\"3. Activated within first 2 months\",",
              "  if(daydiff<90,\"4. Activated within first 3 months\",",
              " if(daydiff<120,\"5. Activated within first 4 months\",",
              " if(daydiff<150,\"6. Activated within first 5 months\",",
              " if(daydiff<180,\"7. Activated within first 6 months\",",
              "\"8. Activated end of season\")))))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "86d65b7f-9d2f-4b18-a4c7-a8cf17e35012",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VW_VIP_ActivationDataset_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2b3df4e9-a607-4799-b1c1-a00cceae0155",
            "sourceColumn": "VW_VIP_ActivationDataset_Mobile",
            "summarizeBy": "none"
          },
          {
            "name": "Same guest different seasons query1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season=Value([Season_ID])",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=27))",
              "",
              "RETURN",
              "IF([Season_ID]=27,",
              "   IF('Query1'[VW_VIP_ActivationDataset_Email] in purchaser_emails_S25,1,IF('Query1'[VW_VIP_ActivationDataset_Email] in purchaser_emails_S26,1,0)),",
              "   IF([Season_ID]=26,",
              "   IF('Query1'[VW_VIP_ActivationDataset_Email] in purchaser_emails_S25,1,IF('Query1'[VW_VIP_ActivationDataset_Email] in purchaser_emails_S27,1,0)),",
              "   IF([Season_ID]=25,",
              "      IF('Query1'[VW_VIP_ActivationDataset_Email] in purchaser_emails_S26,1,IF('Query1'[VW_VIP_ActivationDataset_Email] in purchaser_emails_S27,1,0))",
              "      )))",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4e1314a0-d993-4e24-8b73-96f4c439111e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Same purchaser different seasons query1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season=Value([Season_ID])",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=27))",
              "",
              "RETURN",
              "IF([Season_ID]=27,",
              "   IF('Query1'[Virgin_Email] in purchaser_emails_S25,1,IF('Query1'[Virgin_Email] in purchaser_emails_S26,1,0)),",
              "   IF([Season_ID]=26,",
              "   IF('Query1'[Virgin_Email] in purchaser_emails_S25,1,IF('Query1'[Virgin_Email] in purchaser_emails_S27,1,0)),",
              "   IF([Season_ID]=25,",
              "      IF('Query1'[Virgin_Email] in purchaser_emails_S26,1,IF('Query1'[Virgin_Email] in purchaser_emails_S27,1,0))",
              "      )))",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1f9e95e2-24e1-4369-a52f-819218860483",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Activated_carplate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99e0a1c1-c872-493a-8535-b126196f558c",
            "sourceColumn": "Activated_carplate",
            "summarizeBy": "sum"
          },
          {
            "name": "Sold_OnSite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "403d2507-674c-4592-8808-a84790b37d88",
            "sourceColumn": "Sold_OnSite",
            "summarizeBy": "none"
          },
          {
            "name": "Sold 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(OR(OR([New Category] =\"Mini\", [New Category]=\"Complimentary\"),[New Category]=\"Media Pack\"),0,1)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "66c51493-e83f-4035-9451-886d7ac20953",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MirrorMaze_utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "[VW_VIPActivationDataset_MirrorMaze]-[VW_VIPActivationDataset_MirrorMaze_Remaining]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d90354d3-d12a-48ff-895f-f1e187bc3555",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Auditorium Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "[VW_VIPActivationDataset_Auditorium]-[VW_VIPActivationDataset_Auditorium_Remaining]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "87a4c2ec-9166-4664-993e-d155a6702e68",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Wonderpass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "[VW_VIPActivationDataset_WonderPass]",
              "",
              "// IF([Season_ID]<>27,[VW_VIPActivationDataset_WonderPass],",
              "// IF([VW_VIPActivationDataset_WonderPass]=Blank(),0,",
              "// IF([New Category]=\"1. Private\",3700,",
              "// IF([New Category]=\"2. Diamond\",2850,",
              "// IF([New Category]=\"3. Platinum\",1440,",
              "// IF([New Category]=\"4. Gold\",1150,",
              "// IF([New Category]=\"5. Silver\",740,",
              "// IF([New Category]=\"6. Complimentary\",740,",
              "// IF([New Category]=\"7. Mini\",150,",
              "",
              "// IF([VW_VIPActivationDataset_Category]=\"Media Pack\",[VW_VIPActivationDataset_WonderPass],",
              "// IF([VW_VIPActivationDataset_Category]=\"Media Pack-A\",150",
              "// )))))))))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2efa13af-bdcd-4231-a45d-a8344fc86b5b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "dummy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e1ce2099-4828-4655-b3f8-48aef84a6e5d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Same guest different seasons S28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season=28",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=27))",
              "VAR purchaser_emails_S28=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=28))",
              "",
              "RETURN",
              "   IF('Query1'[VW_VIP_ActivationDataset_Email] in Union(purchaser_emails_S25,purchaser_emails_S26,purchaser_emails_S27),1,0)",
              "/*   ",
              "   Same guest different seasons S27 = ",
              "Var season=27",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query1'[VW_VIP_ActivationDataset_Email]),Filter('Query1',Query1[Season_ID]=27))",
              "",
              "RETURN",
              "   IF('Query1'[VW_VIP_ActivationDataset_Email] in Union(purchaser_emails_S25,purchaser_emails_S26),1,0)",
              "*/"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "327f2cf0-356c-4277-90f2-427df086db85",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Same purchaser different seasons S28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season=28",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=27))",
              "VAR purchaser_emails_S28=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=28))",
              "",
              "RETURN",
              "   IF('Query1'[Virgin_Email] in union(purchaser_emails_S25,purchaser_emails_S26,purchaser_emails_S27),1,0)",
              "",
              "/*Same purchaser different seasons S27 = ",
              "Var season=27",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query1'[Virgin_Email]),Filter('Query1',Query1[Season_ID]=27))",
              "",
              "RETURN",
              "   IF('Query1'[Virgin_Email] in union(purchaser_emails_S25,purchaser_emails_S26),1,0)*/"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3e17cc32-5c6a-4b1a-a199-91a20d2731c3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Entire pack utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              " ",
              " IFERROR(",
              " (",
              "([Entry_Tickets_Utilized]/[VW_VIPActivationDataset_Entry_Tickets])",
              " +",
              "([Parking_Utilized]/[VW_VIPActivationDataset_Parking_Voucher])",
              "+",
              "([Stunt Show Utilized]/[Stunt Show])",
              "+",
              "([Ripleys_Combo_Utilized]/[Ripleys_Combo_Total])",
              "+",
              "([Wonderpass_Utilized]/[Wonderpass])",
              " )/5,0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "0e36ffa5-ace6-4859-a6bd-e7adcd7fa30d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Pack Utilization Groups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF([Entire pack utilization]=0,\"01. 0%\",",
              "IF([Entire pack utilization]<0.1,\"02. 0%-10%\",",
              "IF([Entire pack utilization]<0.2,\"03. 10%-20%\",",
              "IF([Entire pack utilization]<0.3,\"04. 20%-30%\",",
              "IF([Entire pack utilization]<0.4,\"05. 30%-40%\",",
              "IF([Entire pack utilization]<0.5,\"06. 40%-50%\",",
              "",
              "IF([Entire pack utilization]<0.6,\"07. 50%-60%\",",
              "IF([Entire pack utilization]<0.7,\"08. 60%-70%\",",
              "IF([Entire pack utilization]<0.8,\"09. 70%-80%\",",
              "IF([Entire pack utilization]<0.9,\"10. 80%-90%\",",
              "IF([Entire pack utilization]>=0.9,\"11. 90%-100%\"",
              "",
              ")))))))))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7e93ff66-a164-4acb-8ff3-4ba0e03951c4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Entry_Tickets_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "[Entry_Tickets_Utilized]/[VW_VIPActivationDataset_Entry_Tickets]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "cc813a53-a4dc-4130-9fec-17f8d372e02b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "WonderPAss_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "[Wonderpass_Utilized]/[Wonderpass]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "ae47380c-e6a7-4f5c-bf8f-d852fca6e958",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Parking_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "[Parking_Utilized]/[VW_VIPActivationDataset_Parking_Voucher]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "b3d9e4ea-4720-4a22-868c-65a26bcca641",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ripleys_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "IFERROR([Ripleys_Combo_Utilized]/[Ripleys_Combo_Total],0)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "f4377c45-ceae-45a5-bf5d-6a3871b0956b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "VIP_Utilization_Majlis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "991bac76-b43b-43de-8645-dd8095ae8c18",
            "sourceColumn": "VIP_Utilization_Majlis",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP_Utilization_Majlis_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f178bc9d-5553-4835-b4d1-b06bf7e2c686",
            "sourceColumn": "VIP_Utilization_Majlis_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Majlis Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF([VIP_Utilization_Majlis]=BLANK(),Blank(),[VIP_Utilization_Majlis]-[VIP_Utilization_Majlis_Remaining])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c5dc09a9-b245-4c98-a3fa-0f3913768123",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "087f4e2f-a047-424c-8301-405716e8bc79",
        "measures": [
          {
            "name": "Current vs Prev Season Msg",
            "expression": [
              "",
              "\tVAR maxSeason = SELECTEDVALUE('Query1'[Season_ID])",
              "    VAR PrevSeason = SELECTEDVALUE('Compare with'[Value]) ",
              "\tRETURN",
              "\t\t\"Season : \" & maxSeason & \" vs \" & (PrevSeason)"
            ],
            "lineageTag": "ca433e6e-9fa5-4931-9df6-26dde21f2adc"
          },
          {
            "name": "Prev Season Msg",
            "expression": [
              "",
              "\tVAR maxSeason = SELECTEDVALUE('Compare with'[Value]) ",
              "\tRETURN",
              "\t\t\"S\" & maxSeason"
            ],
            "lineageTag": "b10aee94-57e5-48a3-bbc5-0779740e05e1"
          },
          {
            "name": "Activated_Packs_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=VALUE(compare),'Query1'[Activated_carplate]=1)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d10b5014-595c-4fdb-84f5-84010a229a87"
          },
          {
            "name": "Activated_Packs_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "",
              "RETURN",
              " CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=selectedseason,'Query1'[Activated_carplate]=1",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5ef01460-d68f-4134-8771-43dc6401d9a7"
          },
          {
            "name": "Inventory_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(DistinctCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "30c54ead-91ab-4eca-9772-c983553c54ec"
          },
          {
            "name": "Activated_vs_Inventory_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\"  ",
              ""
            ],
            "lineageTag": "d87252ce-f43c-4162-b33e-4c46a1d36966"
          },
          {
            "name": "Current Season Full Msg",
            "expression": [
              "",
              "\tVAR maxSeason = SELECTEDVALUE('Query1'[Season_ID]) ",
              "\tRETURN",
              "\t\t\"Season \" & maxSeason & \" only\""
            ],
            "lineageTag": "28722691-148b-43bf-b461-d9f03ed72a66"
          },
          {
            "name": "Sold_Packs_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=VALUE(compare),'Query1'[Sold 2]=1,ALL('Query1'))  ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d57b9fea-c389-4350-8c9b-3390c9af9b45"
          },
          {
            "name": "Sold_Packs_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=selectedseason,'Query1'[Sold 2]=1) ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4278f648-2d0a-4f9b-96ad-df606e0a7005"
          },
          {
            "name": "Sold_And_Comp_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    CALCULATE(SUM('Query1'[Sold 2]),'Query1'[Season_ID]=selectedseason)+CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Sale_Type]IN{\"Comp - ARN\",\"Comp\",\"Comp - DH\",\"Comp - Mini VIP\"},'Query1'[Activated_carplate]=0,'Query1'[Season_ID]=selectedseason)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "28ed7589-1593-4316-b0a3-5fb88cf88031"
          },
          {
            "name": "Activated_Vs_Sold_And_Comp_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "     \"(\" & ROUND((CALCULATE(SUM('Query1'[Activated_carplate]),'Query1'[Season_ID]=selectedseason)/(CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Sold]=1,'Query1'[Season_ID]=selectedseason)+CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Sale_Type]IN{\"Comp - ARN\",\"Comp\",\"Comp - DH\",\"Comp - Mini VIP\"},'Query1'[Activated_carplate]=0,'Query1'[Season_ID]=selectedseason)))*100,0) & \"% )\"  ",
              ""
            ],
            "lineageTag": "f039b79b-0774-4d3c-a481-05ae2aee8c1d"
          },
          {
            "name": "Sold_Vs_Inventory_Not_Comp_%_selected_season",
            "expression": [
              "",
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Sold 2]=1,'Query1'[Sales_Type_Final]<>\"Comp\",'Query1'[Sales_Type_Final]<>\"Comp - ARN\",'Query1'[Sales_Type_Final]<>\"Comp - DH\",'Query1'[Sales_Type_Final]<>\"Comp - Mini VIP\",'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Sales_Type_Final]<>\"Comp\",'Query1'[Sales_Type_Final]<>\"Comp - ARN\",'Query1'[Sales_Type_Final]<>\"Comp - DH\",'Query1'[Sales_Type_Final]<>\"Comp - Mini VIP\",'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\"",
              ""
            ],
            "lineageTag": "e40795a3-2272-40ba-8cab-423c49d4f3ae"
          },
          {
            "name": "Gold_Activated_selected_season",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Gold\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "11b3735e-89dd-46eb-9253-abf7ec9e4f5d"
          },
          {
            "name": "Gold_Activated_%_selected_season",
            "expression": [
              "",
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "RETURN",
              "",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Gold\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Gold\",'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\"  ",
              ""
            ],
            "lineageTag": "b7ef4937-054c-41bc-b83d-b3b7221b4f01"
          },
          {
            "name": "Silver_Activated_selected_season",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Silver\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)",
              "",
              "  /* This same measure is using for Complimentary Pack.",
              "    But if we use  CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[New Category]=\"6. Complimentary\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected) with Filter(Sale_Type is Comp-Arn, Comp-Dh and Vip Comp",
              "    */",
              ""
            ],
            "formatString": "0",
            "lineageTag": "25694825-6032-4a1a-ab43-48f9ae233daa"
          },
          {
            "name": "Silver_Activated_%_selected_season",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "  \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Silver\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Silver\",'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\" ",
              "    ",
              "",
              "",
              ""
            ],
            "lineageTag": "6b08581e-33a5-4b32-8045-d1cc329be9ff"
          },
          {
            "name": "Platinum_Activated_selected_season",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Platinum\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b92beca6-af82-4d16-9b12-b0543ac7b755"
          },
          {
            "name": "Platinum_Activated_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Platinum\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Platinum\",'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\"  ",
              ""
            ],
            "lineageTag": "168cd837-9966-41db-aae5-2eaebe962384"
          },
          {
            "name": "Mini_Activated_selected_season",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[New Category]=\"7. Mini\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)",
              " "
            ],
            "formatString": "0",
            "lineageTag": "66f9024e-3342-44a4-b662-fc8dee86757b"
          },
          {
            "name": "Mini_Activated_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[New Category]=\"7. Mini\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[New Category]=\"7. Mini\",'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\"  ",
              "",
              "",
              "   /*It is OLD, as here in new category Mini is there but it should be 7. Mini",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[New Category]=\"Mini\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[New Category]=\"Mini\",'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\"  ",
              "   */",
              "",
              ""
            ],
            "lineageTag": "5872f647-975a-40f7-a546-1e38f87f48cf"
          },
          {
            "name": "Diamond_Activated_selected_season",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Diamond\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "170e1720-c0a5-4efe-a535-4ed453745484"
          },
          {
            "name": "Diamond_Activated_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Diamond\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Diamond\",'Query1'[Season_ID]=selectedseason))*100,0) & \"% )\"  ",
              ""
            ],
            "lineageTag": "024f8c43-9c01-470f-9f0f-a120332819eb"
          },
          {
            "name": "Current Season Shortened Msg",
            "expression": [
              "",
              "\tVAR maxSeason = SELECTEDVALUE('Query1'[Season_ID]) ",
              "\tRETURN",
              "\t\t\"S\" & maxSeason "
            ],
            "lineageTag": "743f190c-9c1d-4a52-af63-4d064bfe5df5"
          },
          {
            "name": "Activated_Label",
            "expression": [
              "",
              "var output = \" \"  & \"ACTIVATED\"",
              "return output"
            ],
            "lineageTag": "7a8318d5-8f69-45fa-8d8b-ac8db8740874"
          },
          {
            "name": "Inventory_Label",
            "expression": [
              "",
              "var output = \" \"  & \"INVENTORY\"",
              "return output"
            ],
            "lineageTag": "f1e2bb33-36de-46c7-9400-5e1b917f213f"
          },
          {
            "name": "Unsold_Packs_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Sold 2]=0,'Query1'[Season_ID]=selectedseason) ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "10bfde15-6c39-4570-98b6-73ba66006fcb"
          },
          {
            "name": "Sold_Label",
            "expression": [
              "",
              "var output = \" \"  & \"SOLD\"",
              "return output"
            ],
            "lineageTag": "caab325e-fee6-4831-bfed-d35bb393d68c"
          },
          {
            "name": "Selected_Season_Label",
            "expression": [
              "",
              "var season = SELECTEDVALUE('Query1'[Season_ID])",
              "var output = \" S\"  & season",
              "return output"
            ],
            "lineageTag": "6fd6c31f-ee19-4645-9b36-f87be6730d05"
          },
          {
            "name": "Compared_Season_Label",
            "expression": [
              "",
              "var season = SELECTEDVALUE('Compare with'[Value])",
              "var output = \" S\"  & season",
              "return output"
            ],
            "lineageTag": "a24c61a3-0540-4196-9873-1b1124dd3476"
          },
          {
            "name": "Private_Activated_selected_season",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "",
              "    IF(ISBLANK(CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Private\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)),0,CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Private\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "91cbce1f-194a-4480-be44-c2efa9afdb23"
          },
          {
            "name": "Private_Activated_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "",
              "    \"(\" & IF(ISBLANK(ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Private\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Private\",'Query1'[Season_ID]=selectedseason))*100,0)),0,ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Private\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Private\",'Query1'[Season_ID]=selectedseason))*100,0)) & \"% )\"  ",
              ""
            ],
            "lineageTag": "86218506-9b5b-44c6-85ea-1ef047d9445b"
          },
          {
            "name": "Activated_vs_Inventory_%_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    \"(\" & ROUND((CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=VALUE(compare))/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=VALUE(compare)))*100,0) & \"% )\"  ",
              ""
            ],
            "lineageTag": "eb6f2a65-cbed-480f-9d89-88c4ccd8ff06"
          },
          {
            "name": "Activated_vs_Inventory_%_number_Only_selected_season",
            "displayFolder": "bla",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    (CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selectedseason)/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=selectedseason))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "02a4c2b7-88e3-472c-8de0-d1734c26adb1"
          },
          {
            "name": "Activated_vs_Inventory_%__number_only_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=VALUE(compare))/CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=VALUE(compare))",
              "",
              "",
              ""
            ],
            "formatString": "0.000%;-0.000%;0.000%",
            "lineageTag": "6e523bc7-b43b-45ed-9ae3-3d8165b1fbe0"
          },
          {
            "name": "Entry_Tickets_Utilized_selected_season",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[Entry_Tickets_Utilized]),'Distinct packs'[Season_ID]=selectedseason)   ",
              " "
            ],
            "formatString": "#,0",
            "lineageTag": "5bef98e1-f156-43f5-a2a6-5da6cd478dab"
          },
          {
            "name": "Entry_Tickets_Total_selected_season",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Entry_Tickets]),'Distinct packs'[Season_ID]=selectedseason)   ",
              "// CALCULATE(SUM('Query1'[VW_VIPActivationDataset_Entry_Tickets]),'Query1'[Season_ID]=selectedseason)   ",
              "",
              "",
              "// SUMX(GROUPBY(Query1, Query1[VW_VIP_ActivationDataset_Pack_No],Query1[Season_ID], \"Total Entry Tickets\", MAXX(CURRENTGROUP(), [VW_VIPActivationDataset_Entry_Tickets])), [Total Entry Tickets]) ",
              "",
              "// CALCULATE (",
              "//     SUM ( Query1[VW_VIPActivationDataset_Entry_Tickets] ),",
              "//     FILTER (",
              "//         DISTINCT ( Query1 ),",
              "//         [VW_VIP_ActivationDataset_Pack_No] = MAX ( [VW_VIP_ActivationDataset_Pack_No] )",
              "//             && Query1[Season_ID] =27",
              "//     ))",
              "// )",
              "// CALCULATE (",
              "//     SUMX (",
              "//         SUMMARIZE ( Query1, Query1[VW_VIP_ActivationDataset_Pack_No], Query1[VW_VIPActivationDataset_Entry_Tickets] ),",
              "//         Query1[VW_VIP_ActivationDataset_Pack_No]",
              "//     ),",
              "//     KEEPFILTERS ( Query1[Season_ID] = 27),",
              "//     ALLEXCEPT ( Query1, Query1[Season_ID] )",
              "// ))"
            ],
            "lineageTag": "b5500dd6-85d2-4689-85ae-abb26b5a0caa"
          },
          {
            "name": "Entry_Tickets_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "[Entry_Tickets_Utilized_selected_season]/[Entry_Tickets_Total_selected_season]",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "5b99a0b2-46ca-434d-958e-5b6542c14df0"
          },
          {
            "name": "Entry_Utilized_%_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[Entry_Tickets_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))   ",
              " /",
              "CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Entry_Tickets]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))   ",
              " "
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a072602f-4b26-416f-8489-019335ce3daf"
          },
          {
            "name": "Entry_Utilized_compared_season",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "VAR like_to_like = SELECTEDVALUE('Like to Like'[Value])",
              "VAR selected_park_days=CALCULATE(MAX('Query1'[day_num_tag]),'Query1'[Season_ID]=selectedseason)",
              "VAR compare_park_days=CALCULATE(MAX('Query1'[day_num_tag]),'Query1'[Season_ID]=compare)",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[Entry_Tickets_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))   ",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "2e2267b9-3590-4c59-8e63-ba4ccefbe25a"
          },
          {
            "name": "WonderPass_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    CALCULATE(SUM('Distinct packs'[Wonderpass_Utilized]),'Distinct packs'[Season_ID]=selectedseason)/CALCULATE(SUM('Distinct packs'[Wonderpass]),'Distinct packs'[Season_ID]=selectedseason)     ",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "01d48664-13d3-49c6-8bd0-4a469e3829b7"
          },
          {
            "name": "Wonderpass_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[Wonderpass_Utilized]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "d7122bec-3486-4afc-98ea-e7cedcbd8169"
          },
          {
            "name": "Wonderpass_Utilized_%_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    CALCULATE(SUM('Distinct packs'[Wonderpass_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))/CALCULATE(SUM('Distinct packs'[Wonderpass]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a4156a7d-d004-451a-8039-4e243796068d"
          },
          {
            "name": "Wonderpass_Utilized_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(SUM('Distinct packs'[Wonderpass_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),all('Query1'))",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "67873d9b-889c-4317-a6c4-a53187214fff"
          },
          {
            "name": "Wonderpass_Total_selected_season",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "    CALCULATE(SUM('Distinct packs'[Wonderpass]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "lineageTag": "8796c542-03eb-4467-a1ac-4a80ee3d78dd"
          },
          {
            "name": "Test",
            "expression": [
              "",
              "",
              "VAR perc = ROUND((CALCULATE(SUM('Query1'[Entry_Tickets_Utilized]),'Query1'[Season_ID]=VALUE(25),'Query1'[day_num_tag]<=38)/CALCULATE(SUM('Query1'[VW_VIPActivationDataset_Entry_Tickets]),'Query1'[Season_ID]=VALUE(25),'Query1'[day_num_tag]<=38))*100,0)",
              "VAR utilized_daynum = CALCULATE(SUM('Query1'[Entry_Tickets_Utilized]),'Query1'[Season_ID]=VALUE(25),'Query1'[day_num_tag]<=38)",
              "VAR utilized_wholseason = CALCULATE(SUM('Query1'[Entry_Tickets_Utilized]),'Query1'[Season_ID]=VALUE(25))",
              "VAR total_daynum = CALCULATE(SUM('Query1'[VW_VIPActivationDataset_Entry_Tickets]),'Query1'[Season_ID]=VALUE(25),'Query1'[day_num_tag]<=38)",
              "VAR total_wholeseason = CALCULATE(SUM('Query1'[VW_VIPActivationDataset_Entry_Tickets]),'Query1'[Season_ID]=VALUE(25))",
              "",
              "RETURN",
              "perc & \"Utilized daynum:\" & utilized_daynum & \" Utilized whole season:\" & utilized_wholseason & \" Total daynum:\" & total_daynum & \" Total wholeseason:\" & total_wholeseason"
            ],
            "lineageTag": "c0bfbda5-d32b-4d6e-b62a-aace1eec6ec3"
          },
          {
            "name": "Parking_Total_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Parking_Voucher]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "92d91cbb-4bf1-429d-b443-c417b52a91ce"
          },
          {
            "name": "Parking_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(SUM('Distinct packs'[Parking_Utilized]),'Distinct packs'[Season_ID]=selectedseason)/CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Parking_Voucher]),'Distinct packs'[Season_ID]=selectedseason)     ",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d093e44b-3729-41db-b082-374c114282bd"
          },
          {
            "name": "Parking_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Parking_Utilized]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "12e12d03-963f-401e-b400-74947820d0a5"
          },
          {
            "name": "Parking_Utilized_%_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "",
              "    CALCULATE(SUM('Distinct packs'[Parking_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))/CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Parking_Voucher]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "0d5a7949-8927-420a-ad22-856e51efd269"
          },
          {
            "name": "Parking_Utilized_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Parking_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),all('Query1'))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c0dbacb4-631a-4db1-bdbe-7d85ed4415db"
          },
          {
            "name": "Ripleys_Combo_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Ripleys_Combo_Utilized]),'Distinct packs'[Season_ID]=selectedseason)/CALCULATE(SUM('Distinct packs'[Ripleys_Combo_Total]),'Distinct packs'[Season_ID]=selectedseason)     ",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "c23a3171-ac7b-495d-ab50-f89a23e9408e"
          },
          {
            "name": "Ripleys_Combo_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(SUM('Distinct packs'[Ripleys_Combo_Utilized]),'Distinct packs'[Season_ID]=Value(selectedseason))   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "93bd9c08-f2e8-443e-89f8-5e1f3a43f17a"
          },
          {
            "name": "Ripleys_Combo_Utilized_%_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Ripleys_Combo_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))/CALCULATE(SUM('Distinct packs'[Ripleys_Combo_Total]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "0e4e2df0-6d36-4825-a0bf-463162fba729"
          },
          {
            "name": "Ripleys_Combo_Utilized_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[Ripleys_Combo_Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "537259ea-b82d-4bf7-a75e-10ef62466b78"
          },
          {
            "name": "Ripleys_Combo_Total_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Ripleys_Combo_Total]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "77c75834-c70e-4a78-8104-e4e34ab9452f"
          },
          {
            "name": "VIP_Last_Refresh_Msg",
            "expression": [
              "",
              "var selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "var comparedseason = SELECTEDVALUE('Compare with'[Value])",
              "RETURN",
              " \"Data available : \" & FORMAT(CALCULATE(Min('Query1'[Activated_at]),'Query1'[Season_ID]=VALUE(comparedseason)),\"D-MMM-YY\")  & \" till \" & FORMAT(CALCULATE(Max('Query1'[Activated_at]),'Query1'[Season_ID]=selectedseason),\"D-MMM-YY\")",
              ""
            ],
            "lineageTag": "8ba8ff22-6c47-4a22-aec3-3ae954971aaa"
          },
          {
            "name": "Media_Activated_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "",
              "RETURN",
              "",
              "    \"(\" & ",
              "    IF(",
              "        ISBLANK(",
              "            ROUND((",
              "                CALCULATE(",
              "                    DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),",
              "                    ",
              "                    OR('Query1'[VW_VIPActivationDataset_Category]=\"Media Pack\",",
              "                    'Query1'[VW_VIPActivationDataset_Category]=\"Media Pack-A\"),",
              "                    'Query1'[Activated_carplate]=1,",
              "                    'Query1'[Season_ID]=selectedseason)",
              "        /",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),",
              "            OR('Query1'[VW_VIPActivationDataset_Category]=\"Media Pack\",",
              "            'Query1'[VW_VIPActivationDataset_Category]=\"Media Pack-A\"),",
              "            'Query1'[Season_ID]=selectedseason))*100,0)),0",
              "            ",
              "            ,ROUND(",
              "                (",
              "                    CALCULATE(",
              "                        DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),",
              "                        OR('Query1'[VW_VIPActivationDataset_Category]=\"Media Pack\",",
              "                        'Query1'[VW_VIPActivationDataset_Category]=\"Media Pack-A\"),",
              "                        'Query1'[Activated_carplate]=1,",
              "                        'Query1'[Season_ID]=selectedseason)",
              "                        /",
              "                        CALCULATE(",
              "                            DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),",
              "                        OR('Query1'[VW_VIPActivationDataset_Category]=\"Media Pack\",",
              "                        'Query1'[VW_VIPActivationDataset_Category]=\"Media Pack-A\"),",
              "                        'Query1'[Season_ID]=selectedseason",
              "                        ))*100,0)) & \"% )\"  ",
              ""
            ],
            "lineageTag": "47685bf3-743b-422e-8c65-c1b81db388fb"
          },
          {
            "name": "Media_Activated_selected_season",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),OR('Query1'[VW_VIPActivationDataset_Category]=\"Media Pack\",'Query1'[VW_VIPActivationDataset_Category]=\"Media Pack-A\"),'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5bc78572-05a8-418e-9e47-9078b837f1e9"
          },
          {
            "name": "Data Refresh Details & Availability",
            "expression": [
              "",
              "\tVAR PeopleCountRefresh = FORMAT(CALCULATE(Max('Query1'[Activated_at])),\"D-MMM-YY\") ",
              "\t/*VAR DwellTimeRefresh = FORMAT(CALCULATE(Max('DwellByPavAndDate'[Operation_Date]),ALL('DwellByPavAndDate')),\"D-MMM-YY\")*/ ",
              "   ",
              "RETURN",
              "\"<table style='width:100%'>",
              "  <tr><th></th><th>Last Refresh Date</th><th>Data Source</th><th>Data Availability</th></tr>\" &",
              "  \"<tr><td>VIP Activation</td>\" & \"<td>\" & \"<b>\" & PeopleCountRefresh &  \"</b>\" & \"</td>\"& \"<td> Database (Daily Refresh) </td>\"& \"<td>\" & \"<b>\" & PeopleCountRefresh  &  \"</b>\" & \"</td>\"& \"</tr>\"  &",
              "\"</table>\""
            ],
            "lineageTag": "d7d0e3ed-0a2d-4e3f-91a9-62ea7f0d3fc9"
          },
          {
            "name": "testrip",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "VAR like_to_like = SELECTEDVALUE('Like to Like'[Value])",
              "VAR selected_park_days=CALCULATE(MAX('Query1'[day_num_tag]),'Query1'[Season_ID]=selectedseason)",
              "VAR compare_park_days=CALCULATE(MAX('Query1'[day_num_tag]),'Query1'[Season_ID]=compare)",
              "",
              "RETURN  CALCULATE(SUM('Query1'[Ripleys_Combo_Total]),'Query1'[Season_ID]=VALUE(compare),'Query1'[day_num_tag]<=selected_park_days,ALL('Query1'),'Query1'[day_num_tag]<>BLANK())",
              "",
              "// IF( ",
              "//     AND(like_to_like=\"Same # Of Days\",selected_park_days<compare_park_days),",
              "//    CALCULATE(SUM('Query1'[Ripleys_Combo_Utilized]),'Query1'[Season_ID]=VALUE(compare),'Query1'[day_num_tag]<=selected_park_days,ALL('Query1'),'Query1'[day_num_tag]<>BLANK())/CALCULATE(SUM('Query1'[Ripleys_Combo_Total]),'Query1'[Season_ID]=VALUE(compare),'Query1'[day_num_tag]<=selected_park_days,ALL('Query1'),'Query1'[day_num_tag]<>BLANK()),",
              "//     CALCULATE(SUM('Query1'[Ripleys_Combo_Utilized]),'Query1'[Season_ID]=VALUE(compare),ALL('Query1'),'Query1'[day_num_tag]<>BLANK())/CALCULATE(SUM('Query1'[Ripleys_Combo_Total]),'Query1'[Season_ID]=VALUE(compare),ALL('Query1'),'Query1'[day_num_tag]<>BLANK())",
              "// )"
            ],
            "formatString": "0",
            "lineageTag": "5db81488-f1ee-4f35-b232-64a817fc189f"
          },
          {
            "name": "Silver_Activated_selected_season 2",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[VW_VIPActivationDataset_Category]=\"Silver\",'Query1'[Activated_carplate]=1,'Query1'[Season_ID]=selected)"
            ],
            "formatString": "0",
            "lineageTag": "9c4a918f-7915-4738-a415-f240a5031b7b"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "552fbeb7-a9d7-4f73-a004-96bb82214aa5"
          },
          {
            "name": "Cabana_Total_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Cabana]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "17a78294-6175-4b08-beb8-978fe31ed450"
          },
          {
            "name": "Cabana_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(SUM('Distinct packs'[Cabana Utilized]),'Distinct packs'[Season_ID]=Value(selectedseason))   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b00611c8-8c4b-4e51-96ef-08d6b47ffb0f"
          },
          {
            "name": "Measure 2",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "f24a771d-17f4-4fc0-8123-51ff62a6d82a"
          },
          {
            "name": "StuntShow_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(SUM('Distinct packs'[Stunt Show Utilized]),'Distinct packs'[Season_ID]=Value(selectedseason))   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5bfdb781-6f2f-4933-b671-9507178958d9"
          },
          {
            "name": "Stunt_Total_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Stunt Show]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "53db03e4-4458-4a07-ad71-15eabe2ac740"
          },
          {
            "name": "Cabana_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Cabana Utilized]),'Distinct packs'[Season_ID]=selectedseason)/CALCULATE(SUM('Distinct packs'[Cabana]),'Distinct packs'[Season_ID]=selectedseason)     ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bbe97e1f-e4b6-4ef6-8196-745850d6b723"
          },
          {
            "name": "Stunt_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Stunt Show Utilized]),'Distinct packs'[Season_ID]=selectedseason)/CALCULATE(SUM('Distinct packs'[Stunt Show]),'Distinct packs'[Season_ID]=selectedseason)     ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b8c55276-2828-4d17-be60-241013a1aa10"
          },
          {
            "name": "Measure 3",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "723dbfa1-c67a-4382-8bbb-e04babc4b5ba"
          },
          {
            "name": "Packs_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=VALUE(compare)",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "484727a9-6f36-4565-8f29-491cca9c3f10"
          },
          {
            "name": "Packs_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "",
              "RETURN",
              " CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Pack_No]),'Query1'[Season_ID]=selectedseason)"
            ],
            "formatString": "0",
            "lineageTag": "1a824566-a2fa-4d8a-a1f9-4c6b251d5f73"
          },
          {
            "name": "Purchaser_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[Virgin_Email]),'Query1'[Season_ID]=VALUE(compare)",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "2034c8dd-44e5-4792-a48e-1e60f510d6f6"
          },
          {
            "name": "Purchaser_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[Virgin_Email]),'Query1'[Season_ID]=VALUE(selectedseason)",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "593df156-d5a2-495f-af19-5ab1826d5308"
          },
          {
            "name": "Guest_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Email]),'Query1'[Season_ID]=VALUE(selectedseason)",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "8d7b34d4-cc2a-4afd-b8f5-ee3d02b3a67c"
          },
          {
            "name": "Guest_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Email]),'Query1'[Season_ID]=VALUE(compare)",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "79f7d21a-fe25-4319-bfc5-53a56c737de8"
          },
          {
            "name": "ALL_Label",
            "expression": [
              "",
              "var output = \" \"  & \"INVENTORY\"",
              "return output"
            ],
            "lineageTag": "c59ab923-55a8-43ee-9a87-afdaf211fd6e"
          },
          {
            "name": "Repeat purchasers %",
            "expression": [
              "",
              "",
              "CALCULATE(DISTINCTCOUNT('Query1'[Virgin_Email]),'Query1'[Same purchaser different seasons S28]=1)/[Purchaser_selected_season]",
              "//[Same purchaser different seasons selected season]/[Purchaser_selected_season]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5cb249c2-4dca-45c4-b5af-030ed8fe4bc2"
          },
          {
            "name": "Repeat guests %",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT('Query1'[VW_VIP_ActivationDataset_Email]),'Query1'[Same guest different seasons S28]=1)/[Guest_selected_season]",
              "//[Same guest different seasons selected season]/[Guest_selected_season]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b3bc80f5-9c50-43f1-9162-68a4f7f35311"
          },
          {
            "name": "Ripleys_MM_Total_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_MirrorMaze]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "407ccd7d-3d17-43a4-84d0-5d5a95146668"
          },
          {
            "name": "Ripleys_auditorium_Total_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Auditorium]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "cb23c13f-c94a-4c17-acaa-5b1c9c8e2015"
          },
          {
            "name": "Ripleys_MM_Total_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_MirrorMaze]),'Distinct packs'[Season_ID]=Value(compare))   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5513305e-3c09-46e8-b7a1-c15d7b87caa9"
          },
          {
            "name": "Ripleys_Auditorium_Total_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Auditorium]),'Distinct packs'[Season_ID]=Value(compare),all(query1))   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "28abdf34-7234-4568-a03f-7cf26f6c02cc"
          },
          {
            "name": "Ripleys_MM_Utilized_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[MirrorMaze_utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ad58ae2c-cd7b-4e92-843e-88da96519ad0"
          },
          {
            "name": "Ripleys_Auditorium_Utilized_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[Auditorium Utilized]),'Distinct packs'[Season_ID]=VALUE(compare),ALL('Query1'))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "e9548ff7-1f98-44f7-b2a0-a642af169818"
          },
          {
            "name": "Ripleys_MM_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[MirrorMaze_utilized]),'Distinct packs'[Season_ID]=VALUE(selectedseason))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "806d3ca1-5311-4bf0-9cb0-a3600b5622c8"
          },
          {
            "name": "Ripleys_Auditorium_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "CALCULATE(SUM('Distinct packs'[Auditorium Utilized]),'Distinct packs'[Season_ID]=VALUE(selectedseason))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "97e6966a-d681-45b3-8abb-20a4a3832abd"
          },
          {
            "name": "Ripleys_Auditorium_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Auditorium Utilized]),'Distinct packs'[Season_ID]=selectedseason)/CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Auditorium]),'Distinct packs'[Season_ID]=selectedseason)     ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e108accf-4cd1-498a-be7e-c18b048b9ed7"
          },
          {
            "name": "Ripleys_Auditorium_Utilized_%_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Auditorium Utilized]),'Distinct packs'[Season_ID]=Value(compare),all(Query1))/CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_Auditorium]),'Distinct packs'[Season_ID]=Value(compare),all(Query1))     ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2560d148-c672-4200-a90f-4a2deb307d85"
          },
          {
            "name": "Ripleys_MM_Utilized_%_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[MirrorMaze_utilized]),'Distinct packs'[Season_ID]=Value(compare),ALL(Query1))/CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_MirrorMaze]),'Distinct packs'[Season_ID]=Value(compare),ALL(Query1))     ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "981e3586-9f5d-402f-9d94-52cea8e6c3de"
          },
          {
            "name": "Ripleys_MM_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[MirrorMaze_utilized]),'Distinct packs'[Season_ID]=Value(selectedseason))/CALCULATE(SUM('Distinct packs'[VW_VIPActivationDataset_MirrorMaze]),'Distinct packs'[Season_ID]=Value(selectedseason))     ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8be07e6c-ad2c-4828-a6bd-7efd9e661f52"
          },
          {
            "name": "Majlis_Utilized_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(SUM('Distinct packs'[Majlis Utilized]),'Distinct packs'[Season_ID]=Value(selectedseason))   ",
              ""
            ],
            "lineageTag": "315244db-207a-4625-8b39-51a3a25c906b"
          },
          {
            "name": "Majlis_Total_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[VIP_Utilization_Majlis]),'Distinct packs'[Season_ID]=selectedseason)   ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "3778ecb2-390f-4f83-8217-2457abb7845a"
          },
          {
            "name": "Majlis_Utilized_%_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(SUM('Distinct packs'[Majlis Utilized]),'Distinct packs'[Season_ID]=selectedseason)/CALCULATE(SUM('Distinct packs'[VIP_Utilization_Majlis]),'Distinct packs'[Season_ID]=selectedseason)     ",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "91e4b0dd-f18d-47e7-a153-fc2af5417761"
          }
        ],
        "partitions": [
          {
            "name": "Query1-5b6b3c45-bc58-415b-875d-d236b0b025ed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\" = Workspaces{[workspaceId=\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"]}[Data],",
                "    #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\" = #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"{[dataflowId=\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"]}[Data],",
                "    Query1_ = #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"{[entity=\"Query1\",version=\"\"]}[Data]",
                "in",
                "    Query1_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_457552a2-3594-43b7-be53-c6fd1b316588",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "79f78569-1be4-4580-834d-8bd4e13c8300",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "60ec053d-e807-41ba-8c2f-ac20a19f2432",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bdc49bdb-3da4-4d67-a29c-82a486caf304",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6884b73b-44d8-4aff-b5b3-036d74678554",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "779bdb3f-e201-4d12-8638-9d4cf88dc340",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "afb8bbf2-2eec-40ae-ae7d-50920dbe6805",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d7166fa0-56ad-4583-a4c8-5a92a339638f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "30a720e1-6715-4b83-800c-141bf6fa14e6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "57cf0e02-422a-4461-b808-ad94b8e5276a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9c235c73-a591-4a57-85d4-09f76a43b283",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0c53cbc7-ddc5-49d5-a63b-c8f784618be0",
                "ordinal": 3
              }
            ],
            "lineageTag": "29fd9310-d529-4f2b-bb41-2019cf4d0e15"
          }
        ],
        "isHidden": true,
        "lineageTag": "83cb36b8-2681-46ef-be7c-831a7e70544d",
        "partitions": [
          {
            "name": "LocalDateTable_457552a2-3594-43b7-be53-c6fd1b316588-80b7138c-3143-47dd-bcfa-412ef410d431",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Query1'[VW_VIPActivationDataset_DOB])), 1, 1), Date(Year(MAX('Query1'[VW_VIPActivationDataset_DOB])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Query2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VIP_Utilization_Purchaser_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f16e06f2-7d9b-4fb8-934c-d7bdd1403bc3",
            "sourceColumn": "VIP_Utilization_Purchaser_Name",
            "summarizeBy": "none"
          },
          {
            "name": "VIP_Utilization_Pack_Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "25ee5c95-f301-4a4a-9071-f26b4ef1ca3b",
            "sourceColumn": "VIP_Utilization_Pack_Number",
            "summarizeBy": "sum"
          },
          {
            "name": "VW_VIP_ActivationDataset_Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f4ab700-e415-48c8-bf7d-1bb2841b77fd",
            "sourceColumn": "VW_VIP_ActivationDataset_Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Same_Person_Activated_And_Purchased",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "46161481-28d2-4cd5-8f4b-00e7ac1dd7c5",
            "sourceColumn": "Same_Person_Activated_And_Purchased",
            "summarizeBy": "sum"
          },
          {
            "name": "Purchaser Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "529333c8-81e6-499f-affa-3b48ad02936e",
            "sourceColumn": "Purchaser Email",
            "summarizeBy": "none"
          },
          {
            "name": "Guest Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a061a37d-afc5-4722-8bbd-68d1d3a4fdf7",
            "sourceColumn": "Guest Email",
            "summarizeBy": "none"
          },
          {
            "name": "Season_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ff89159-9616-4f85-acce-276919d94fc8",
            "sourceColumn": "Season_ID",
            "summarizeBy": "count"
          },
          {
            "name": "Season+Pack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f99efdd1-2a99-42b3-86b5-0d2e36b76a03",
            "sourceColumn": "Season+Pack",
            "summarizeBy": "none"
          },
          {
            "name": "day_num_tag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "54def392-d375-43c2-9ee6-afff41da3934",
            "sourceColumn": "day_num_tag",
            "summarizeBy": "sum"
          },
          {
            "name": "Activated_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3cc86b5b-72d9-4a73-859f-2b8e8ff48646",
            "sourceColumn": "Activated_at",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_59a958fb-ab4d-4811-b12b-6b0ebd526453"
                },
                "isDefault": true,
                "relationship": "0d0ec51b-86b6-441f-b0e3-62b83c055b85"
              }
            ]
          },
          {
            "name": "Same guest different seasons query2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season=Value([Season_ID])",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query2'[Guest Email]),Filter('Query2',Query2[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query2'[Guest Email]),Filter('Query2',Query2[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query2'[Guest Email]),Filter('Query2',Query2[Season_ID]=27))",
              "",
              "RETURN",
              "IF([Season_ID]=27,",
              "   IF('Query2'[Guest Email] in purchaser_emails_S25,1,IF('Query2'[Guest Email] in purchaser_emails_S26,1,0)),",
              "   IF([Season_ID]=26,",
              "   IF('Query2'[Guest Email] in purchaser_emails_S25,1,IF('Query2'[Guest Email] in purchaser_emails_S27,1,0)),",
              "   IF([Season_ID]=25,",
              "      IF('Query2'[Guest Email] in purchaser_emails_S26,1,IF('Query2'[Guest Email] in purchaser_emails_S27,1,0))",
              "      )))",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6e295a13-f71b-4e4a-ba5e-5ff571186fe2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Same purchaser different seasons query2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season=Value([Season_ID])",
              "",
              "VAR purchaser_emails_S25=CALCULATETABLE(DISTINCT('Query2'[Purchaser Email]),Filter('Query2',Query2[Season_ID]=25))",
              "VAR purchaser_emails_S26=CALCULATETABLE(DISTINCT('Query2'[Purchaser Email]),Filter('Query2',Query2[Season_ID]=26))",
              "VAR purchaser_emails_S27=CALCULATETABLE(DISTINCT('Query2'[Purchaser Email]),Filter('Query2',Query2[Season_ID]=27))",
              "",
              "RETURN",
              "IF([Season_ID]=27,",
              "   IF('Query2'[Purchaser Email] in purchaser_emails_S25,1,IF('Query2'[Purchaser Email] in purchaser_emails_S26,1,0)),",
              "   IF([Season_ID]=26,",
              "   IF('Query2'[Purchaser Email] in purchaser_emails_S25,1,IF('Query2'[Purchaser Email] in purchaser_emails_S27,1,0)),",
              "   IF([Season_ID]=25,",
              "      IF('Query2'[Purchaser Email] in purchaser_emails_S26,1,IF('Query2'[Purchaser Email] in purchaser_emails_S27,1,0))",
              "      )))",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "9ba35aa7-e4d5-4c72-8ed4-242413370d3d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "VIP_Utilization_Purchaser_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "416f297a-631b-4f32-a346-df9a0afbb35d",
            "sourceColumn": "VIP_Utilization_Purchaser_Mobile",
            "summarizeBy": "none"
          },
          {
            "name": "VIP_Utilization_Guest_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a92ffce-d034-4450-861e-d7ace21eca24",
            "sourceColumn": "VIP_Utilization_Guest_Mobile",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ac04dbae-74ea-4c28-8f5f-dd910de2ef05",
        "measures": [
          {
            "name": "Same_Person_Activated_Purchased_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "VAR like_to_like = SELECTEDVALUE('Like to Like'[Value])",
              "VAR selected_park_days=CALCULATE(MAX('Query2'[day_num_tag]),'Query2'[Season_ID]=selectedseason)",
              "VAR compare_park_days=CALCULATE(MAX('Query2'[day_num_tag]),'Query2'[Season_ID]=compare,ALL('Query1'))",
              "",
              "RETURN",
              "",
              "IF( ",
              "    AND(like_to_like=\"Same # Of Days\",selected_park_days<compare_park_days),",
              "    CALCULATE(SUM('Query2'[Same_Person_Activated_And_Purchased]),'Query2'[Season_ID]=compare,'Query2'[day_num_tag]<=selected_park_days,ALL('Query1')),",
              "    CALCULATE(SUM('Query2'[Same_Person_Activated_And_Purchased]),'Query2'[Season_ID]=compare,ALL('Query1'))",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1c0242fb-38e8-4718-99b8-1590a7e20af9"
          },
          {
            "name": "Same_Person_Activated_Purchased_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "VAR like_to_like = SELECTEDVALUE('Like to Like'[Value])",
              "VAR selected_park_days=CALCULATE(MAX('Query2'[day_num_tag]),'Query2'[Season_ID]=selectedseason)",
              "VAR compare_park_days=CALCULATE(MAX('Query2'[day_num_tag]),'Query2'[Season_ID]=compare,ALL('Query1'))",
              "",
              "RETURN",
              "",
              "IF( ",
              "    AND(like_to_like=\"Same # Of Days\",selected_park_days>compare_park_days),",
              "    CALCULATE(SUM('Query2'[Same_Person_Activated_And_Purchased]),'Query2'[Season_ID]=VALUE(selectedseason),'Query2'[day_num_tag]<=compare_park_days),",
              "    CALCULATE(SUM('Query2'[Same_Person_Activated_And_Purchased]),'Query2'[Season_ID]=VALUE(selectedseason))",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c85ae4b6-d924-4129-8ecd-6e7dafb1d1c9"
          },
          {
            "name": "Females_Activated_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(Count('Query2'[VIP_Utilization_Pack_Number]),'Query2'[Season_ID]=VALUE(selectedseason),'Query2'[VW_VIP_ActivationDataset_Gender]=\"female\")  "
            ],
            "formatString": "0",
            "lineageTag": "9bafd613-677e-4e8e-9ff6-a2245e01d48a"
          },
          {
            "name": "Females_Activated_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(Count('Query2'[VIP_Utilization_Pack_Number]),'Query2'[Season_ID]=VALUE(compare),'Query2'[VW_VIP_ActivationDataset_Gender]=\"female\",ALL('Query1') ) "
            ],
            "formatString": "0",
            "lineageTag": "8cea1c4e-66db-4b14-a02a-cf88f050150e"
          },
          {
            "name": "Males_Activated_selected_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "",
              "CALCULATE(Count('Query2'[VIP_Utilization_Pack_Number]),'Query2'[Season_ID]=VALUE(selectedseason),'Query2'[VW_VIP_ActivationDataset_Gender]=\"male\")  "
            ],
            "formatString": "0",
            "lineageTag": "36c7a00b-8483-4540-91ee-7192ad607525"
          },
          {
            "name": "Males_Activated_compared_season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "VAR result = CALCULATE(Count('Query2'[VIP_Utilization_Pack_Number]),'Query2'[Season_ID]=VALUE(compare),'Query2'[VW_VIP_ActivationDataset_Gender]=\"male\",ALL('Query1')) ",
              "RETURN",
              "",
              "IF(ISBLANK(result),0,result)"
            ],
            "formatString": "0",
            "lineageTag": "d81f1a9c-fad9-4804-b030-badde0791fbb"
          },
          {
            "name": "Measure 4",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "ec65e851-6cbd-4cdb-855a-6577a551e149"
          },
          {
            "name": "Same guest different seasons selected season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query2'[Guest Email]),'Query2'[Season_ID]=VALUE(selectedseason),'Query2'[Same guest different seasons query2]=1)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4e608577-712d-43f2-b01f-b7960aad3962"
          },
          {
            "name": "Same guest different seasons compared season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query2'[Guest Email]),'Query2'[Season_ID]=VALUE(compare),'Query2'[Same guest different seasons query2]=1)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "6437d27f-0e6c-4095-beec-ab52fcfd6a18"
          },
          {
            "name": "Same purchaser different seasons selected season",
            "expression": [
              "",
              "VAR selectedseason = SELECTEDVALUE('Query1'[Season_ID])",
              "VAR compare = SELECTEDVALUE('Compare with'[Value])",
              "",
              "RETURN",
              "    CALCULATE(DISTINCTCOUNT('Query2'[Purchaser Email]),'Query2'[Season_ID]=VALUE(selectedseason),'Query2'[Same guest different seasons query2]=1)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1965ba94-9256-4695-b9db-1ee9b1226d48"
          }
        ],
        "partitions": [
          {
            "name": "Query2-1ecfbb1b-6bdc-4d7e-b562-5a488edf0797",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\" = Workspaces{[workspaceId=\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"]}[Data],",
                "    #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\" = #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"{[dataflowId=\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"]}[Data],",
                "    Query2_ = #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"{[entity=\"Query2\",version=\"\"]}[Data]",
                "in",
                "    Query2_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Compare with",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "853aeb25738245da8376e65248ee626e"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "109c7a2b-1eb7-4f68-a177-d980ad63e1f8",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5025edf6-913f-49a8-8213-3d733151885b",
        "partitions": [
          {
            "name": "Compare with-eafe38f8-376b-467a-8919-32b6f264f928",
            "mode": "import",
            "source": {
              "expression": "{CONVERT(22,INTEGER),CONVERT(23,INTEGER),CONVERT(24,INTEGER),CONVERT(25,INTEGER),CONVERT(26,INTEGER),CONVERT(27,INTEGER)}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Like to Like",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c7583b71d8a3411b993f384fab53d64e"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3a29b945-742a-493e-a567-9a2e78de27b3",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3955e641-f96c-4d51-a3d3-b798efba7a27",
        "partitions": [
          {
            "name": "Like to Like-7b16558f-a951-4ab5-ae0f-f3438b7380b2",
            "mode": "import",
            "source": {
              "expression": "{\"Same # Of Days\",\"ETD\"}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_13c1f7c3-4b1d-4af5-b5be-c53dea229164",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "91e0cfec-ac4d-41b8-8078-8bf004cb6b2f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5c5f6f38-c1cb-4c30-9897-90fb7f61cc15",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cfb01346-513e-437c-b321-519c14d1dc99",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9fb7f9bb-3e7a-4c3f-890e-6a8b3a8b2c8e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b415de89-d3d2-4a01-a4ff-0cf079bb44ee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8223f2ac-36bf-472c-ad44-f97648ebaf05",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3b70f594-08cd-4ce7-84cf-4c33bd56abba",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "cd869a62-cd0e-4f26-9dda-45b562f5cd96",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c050153b-3916-4856-9e32-c03ccb4b9f5f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d1455613-1ca6-4597-8b6d-1e3f16f01e44",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1a658cc7-9d29-49ac-9d27-edd23f0fd931",
                "ordinal": 3
              }
            ],
            "lineageTag": "491e3e6d-311d-46fb-8e34-d2f0210888a8"
          }
        ],
        "isHidden": true,
        "lineageTag": "a4930f7b-aa47-4981-8e68-8af050f1ef64",
        "partitions": [
          {
            "name": "LocalDateTable_13c1f7c3-4b1d-4af5-b5be-c53dea229164-53b18f49-c73f-4fe6-9bae-b28fb3d75678",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Query1'[Activated_at])), 1, 1), Date(Year(MAX('Query1'[Activated_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Venn Diagram",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d9fbc8806bce4ee3a7246653bf04cacf"
          }
        ],
        "columns": [
          {
            "name": "Entry Tickets Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "fe60d370-94d8-461b-9100-4d939114565c",
            "sourceColumn": "[Value1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Wonderpass Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "717dd70f-c8c6-4e25-a6d8-3d12359709b7",
            "sourceColumn": "[Value2]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parking Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "11b5e83f-f038-4d82-ac14-f1e46ce20fa3",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ripleys Combo Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "b03e0fba-26ac-4505-a217-bba285ed885e",
            "sourceColumn": "[Value4]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Count of Pack Nos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "1ea07735-d7ed-46b0-bbb5-61f7c33ae9a4",
            "sourceColumn": "[Value5]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2d46005c-53f7-4321-ba70-7bcc7074efb7",
        "measures": [
          {
            "name": "Max_Season_label",
            "expression": [
              "",
              "VAR maxSeason = CALCULATE(MAX('Query1'[Season_ID]))",
              "RETURN",
              "\"Season \" & maxSeason & \" only\""
            ],
            "lineageTag": "c5c618dc-f797-4052-824e-a0ea61ec975e"
          }
        ],
        "partitions": [
          {
            "name": "Venn Diagram-59d91188-17f6-4e93-90fa-0cdf81073921",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (0,0,0,0,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]=0)",
                "    ),",
                "    (0,0,0,1,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (0,0,1,1,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (0,1,1,1,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (1,1,1,1,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (0,0,1,0,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]=0)",
                "    ),",
                "    (0,1,0,0,",
                "     CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]=0)",
                "    ),",
                "    (0,1,0,1,",
                "     CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (0,1,1,0,",
                "     CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]=0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]=0)",
                "    ),",
                "    (1,0,0,0,",
                "     CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]=0)",
                "    ),",
                "    (1,0,0,1,",
                "     CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (1,0,1,0,",
                "      CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]=0)",
                "    ),",
                "    (1,0,1,1,",
                "      CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]=0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (1,1,0,0,",
                "      CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]=0) ",
                "    ),",
                "    (1,1,0,1",
                "    ,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]=0,'Distinct packs'[Ripleys_Combo_Utilized]>0)",
                "    ),",
                "    (1,1,1,0,",
                "    CALCULATE(COUNT('Distinct packs'[VW_VIP_ActivationDataset_Pack_No]),'Distinct packs'[Season_ID]=MAX('Distinct packs'[Season_ID]),",
                "    'Distinct packs'[Entry_Tickets_Utilized]>0,'Distinct packs'[Wonderpass_Utilized]>0,'Distinct packs'[Parking_Utilized]>0,'Distinct packs'[Ripleys_Combo_Utilized]=0)",
                "    )",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "VIP_WonderPassPlaysByCategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Season_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01133520-9520-4927-adde-4053ec4e20a2",
            "sourceColumn": "Season_ID",
            "summarizeBy": "count"
          },
          {
            "name": "MediaCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8744da1b-a3a8-490b-bf1a-f68f519ccb3d",
            "sourceColumn": "MediaCode",
            "summarizeBy": "none"
          },
          {
            "name": "Game_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "606cb677-0702-4064-bbc8-c17b9c6cbe41",
            "sourceColumn": "Game_Category",
            "summarizeBy": "none"
          },
          {
            "name": "Total_Spent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b0338443-a69b-41fd-9bbc-0a8322aede73",
            "sourceColumn": "Total_Spent",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "92e07840-7fba-4c5f-8a10-df7a247c8f3f",
        "partitions": [
          {
            "name": "VIP_WonderPassPlaysByCategory-c93d24fd-1e98-4cd7-9228-69bd55c8b82d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\" = Workspaces{[workspaceId=\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"]}[Data],",
                "    #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\" = #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"{[dataflowId=\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"]}[Data],",
                "    VIP_WonderPassPlaysByCategory_ = #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"{[entity=\"VIP_WonderPassPlaysByCategory\",version=\"\"]}[Data]",
                "in",
                "    VIP_WonderPassPlaysByCategory_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6560ee15-3699-48a4-b15e-ec59a82c404c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6b3eabbc-7093-4928-8410-44223eab2cf1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3a7308a9-24dc-4ee2-9cd4-16c7d641e3cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ccb0600e-8c9e-4c09-b009-bcec8d8a391d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f086724a-d7ff-4e2d-9513-135ba152cfcb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c062d810-121d-4b4a-b319-b1236596433e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2a0bfb5b-5c5e-4181-b94f-2123241502e8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d4e46681-341e-41ff-9510-5dcda96fcf94",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "30080db5-6135-46e4-a9ce-f434aa598ab5",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0f8428ef-5aff-4253-bafb-42ce02f4da7a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d68cddcf-7400-4113-989c-eeaa373a5b50",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fafd63b5-377c-4066-867e-6aa484035fcd",
                "ordinal": 3
              }
            ],
            "lineageTag": "e2c1fff0-3366-483a-95ed-bb792088b7fb"
          }
        ],
        "isHidden": true,
        "lineageTag": "ef0f1459-bfae-42c3-8204-cd72fb8414ba",
        "partitions": [
          {
            "name": "LocalDateTable_6560ee15-3699-48a4-b15e-ec59a82c404c-f880f08e-6ce1-4400-9f69-31de5eeac982",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Query1'[SaleDate])), 1, 1), Date(Year(MAX('Query1'[SaleDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_59a958fb-ab4d-4811-b12b-6b0ebd526453",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6dbf37b3-5e3f-4157-9321-f7cc109a1e99",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e8b88b14-1fe9-41d6-ab05-0dae38689ac5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c541025e-d08c-4621-9498-36e57e2e955b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f8ba17c0-5ca2-428b-b3b1-43925fe9305c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f851fbbd-438d-4c2d-b682-77323b42e1fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f30ea836-d0f3-4b36-9e8e-74dbca2cf049",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9b4b3368-e62d-4d6a-9271-c9debb50afd9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8a89ffef-dc12-47d2-b1be-001a29bf1570",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1c1eac22-ab65-4900-b4eb-56a00628b636",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b30694e6-877c-4aaf-af6c-a0e6cb591468",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d35d9e3d-fb2f-45ae-81de-b66cdbea8365",
                "ordinal": 3
              }
            ],
            "lineageTag": "ba0d0ee3-71c7-4cec-bcef-108bf62ec4b0"
          }
        ],
        "isHidden": true,
        "lineageTag": "80472a7d-9916-4b4b-a08e-6a95f85ea03b",
        "partitions": [
          {
            "name": "LocalDateTable_59a958fb-ab4d-4811-b12b-6b0ebd526453-72618b9a-cc9e-4bdd-a4a6-dc937476b31f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Query2'[Activated_at])), 1, 1), Date(Year(MAX('Query2'[Activated_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "VIP_Parking",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Op_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1b461c41-92ef-4767-8cba-47f11dd8933b",
            "sourceColumn": "Op_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3b61af33-bad5-4f12-8b5d-d0f12bdd4798"
                },
                "isDefault": true,
                "relationship": "83cfe3bf-6936-4221-b678-25217bd5f172"
              }
            ]
          },
          {
            "name": "Hr_Str",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "7299a19f-e5d0-4018-af0f-03861d3bb1e1",
            "sourceColumn": "Hr_Str",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP1 Occ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2989d767-7a3a-4133-b1cb-af8949aa24c4",
            "sourceColumn": "VIP1 Occ",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP2 Occ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "735ee488-7676-414f-8f52-7dd878142b8b",
            "sourceColumn": "VIP2 Occ",
            "summarizeBy": "sum"
          },
          {
            "name": "Season_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "58f0d844-9b0d-4036-8d6d-38fbac30ecf4",
            "sourceColumn": "Season_id",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP1_Entry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f64a164-cdf9-48aa-a219-5a618e8b7ef9",
            "sourceColumn": "VIP1_Entry",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP1_Exit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "709e08ff-0805-4d6b-95e8-c3f5b8744b4e",
            "sourceColumn": "VIP1_Exit",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP2_Entry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "408866a5-3409-4b52-a987-e126b9af91a7",
            "sourceColumn": "VIP2_Entry",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP2_Exit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "651c8517-0a7e-4f6d-a331-baa05e6a80cd",
            "sourceColumn": "VIP2_Exit",
            "summarizeBy": "sum"
          },
          {
            "name": "Premium_Entry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1881f124-f460-4212-9aa4-56a23ea652b6",
            "sourceColumn": "Premium_Entry",
            "summarizeBy": "sum"
          },
          {
            "name": "Premium_Exit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b0551ba0-0908-48a5-9076-fefbe7ab7c91",
            "sourceColumn": "Premium_Exit",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP1_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c850fba-724d-4cff-b3f6-2edab9eb40ec",
            "sourceColumn": "VIP1_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP2_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9cc255e0-925c-4777-9545-1175b032a961",
            "sourceColumn": "VIP2_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Premium_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84cb823f-7250-4402-b902-0750b076b816",
            "sourceColumn": "Premium_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP1_occupancy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3997d945-77be-4c9a-9a64-64e91bc633bf",
            "sourceColumn": "VIP1_occupancy",
            "summarizeBy": "sum"
          },
          {
            "name": "VIP2_occupancy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c00061c1-54d1-49a6-a84d-63002b42c62d",
            "sourceColumn": "VIP2_occupancy",
            "summarizeBy": "sum"
          },
          {
            "name": "Premium_occupancy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "186400fc-4159-47a9-9c71-ab7fbb624eb8",
            "sourceColumn": "Premium_occupancy",
            "summarizeBy": "sum"
          },
          {
            "name": "Premium Occ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1cedadf9-05e6-4187-90d7-8afe8bd0ede4",
            "sourceColumn": "Premium Occ",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "32319580-804d-4b54-97d5-2c33f8fd2b8e",
        "measures": [
          {
            "name": "Vip1_Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "var selected_season= SELECTEDVALUE('Query1'[Season_ID])",
              "RETURN CALCULATE(MEDIAN('VIP_Parking'[VIP1 Occ]),'VIP_Parking'[VIP1 Occ]>0,VIP_Parking[Season_id]=selected_season)",
              " ",
              " //CALCULATE(MEDIAN('VIP_Parking'[VIP1 Occ]),'VIP_Parking'[VIP1 Occ]>0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0fa70c11-0036-48ee-97ff-0039217eed23"
          },
          {
            "name": "Vip2_Avg",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "var selected_season= SELECTEDVALUE('Query1'[Season_ID])",
              "RETURN CALCULATE(MEDIAN('VIP_Parking'[VIP2 Occ]),'VIP_Parking'[VIP2 Occ]>0,VIP_Parking[Season_id]=selected_season)",
              "",
              "//CALCULATE(MEDIAN('VIP_Parking'[VIP2 Occ]),'VIP_Parking'[VIP2 Occ]>0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "22d33b1b-184c-4b4d-a4b3-21e2aadd1987"
          }
        ],
        "partitions": [
          {
            "name": "VIP_Parking-49ab24f5-cd28-4afe-ba3e-0e61db10f042",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\" = Workspaces{[workspaceId=\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"]}[Data],",
                "    #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\" = #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"{[dataflowId=\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"]}[Data],",
                "    VIP_Parking_ = #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"{[entity=\"VIP_Parking\",version=\"\"]}[Data]",
                "in",
                "    VIP_Parking_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Distinct packs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "186418ce64eb42b49175bf4ae2ea59a9"
          }
        ],
        "columns": [
          {
            "name": "Season+Pack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "10053064-d63f-426a-859f-d45ea0f16279",
            "sourceColumn": "Query1[Season+Pack]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Season_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "30b0f2d8-572e-40f7-bb2d-0c3e19160122",
            "sourceColumn": "Query1[Season_ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Virgin_Pack_No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "47718ecc-5614-46e9-a593-5743ee690ff6",
            "sourceColumn": "Query1[Virgin_Pack_No]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Virgin_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a07dc1d5-05d8-4242-8b76-ff8c9b0d8a90",
            "sourceColumn": "Query1[Virgin_Email]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIP_ActivationDataset_Pack_No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "51aab050-9ef2-465f-bbb5-5846bbb449ec",
            "sourceColumn": "Query1[VW_VIP_ActivationDataset_Pack_No]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b04356ab-08cd-455b-89d1-dfb527d607cb",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Category]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Sale_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c28ada7e-4e51-4db8-9bad-aa0dbfc690bc",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Sale_Type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_DOB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4327d11d-7904-495d-acc9-609005ce2b76",
            "sourceColumn": "Query1[VW_VIPActivationDataset_DOB]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1a28d957-6c5d-4faa-90d9-a455f0254878"
                },
                "isDefault": true,
                "relationship": "7f0fe410-4544-4181-b96b-2530c3a012f7"
              }
            ]
          },
          {
            "name": "VW_VIPActivationDataset_Nationality",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c020418f-31f3-4648-baf4-c1e2e65f6808",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Nationality]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Entry_Tickets",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3b3457c7-ebb7-4b33-8c1f-9e63643b2d66",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Entry_Tickets]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Entry_Tickets_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "aca5bb6f-7af8-45e7-8004-cc2b59934040",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Entry_Tickets_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_WonderPass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "25f327dc-1066-49c5-b97d-42d0c590ead2",
            "sourceColumn": "Query1[VW_VIPActivationDataset_WonderPass]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_WonderPass_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ea9e8a3c-2302-4229-b60d-398343d7aa13",
            "sourceColumn": "Query1[VW_VIPActivationDataset_WonderPass_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Parking_Voucher",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9901f6d5-4488-4605-86cd-d216644b4064",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Parking_Voucher]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Parking_Voucher_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "beb2bdf3-fc33-4bb9-b7ea-571a283f0dcf",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Parking_Voucher_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Auditorium",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c96bba7f-c83b-43f6-9df9-cbea5e5179fb",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Auditorium]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_Auditorium_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a1280d2b-88a1-4716-95a0-f72fe8ac344b",
            "sourceColumn": "Query1[VW_VIPActivationDataset_Auditorium_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_MirrorMaze",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "537c216a-943e-4b60-8670-2670d708a5ba",
            "sourceColumn": "Query1[VW_VIPActivationDataset_MirrorMaze]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIPActivationDataset_MirrorMaze_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3f00c435-79f7-4881-89da-ce86674e7667",
            "sourceColumn": "Query1[VW_VIPActivationDataset_MirrorMaze_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VW_VIP_ActivationDataset_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9a763c2a-b10d-45eb-a889-295410b776a6",
            "sourceColumn": "Query1[VW_VIP_ActivationDataset_Email]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VIP_Utilization_Sold_OnSite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a900a47d-5678-4232-947e-2ec4a9199161",
            "sourceColumn": "Query1[VIP_Utilization_Sold_OnSite]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Activated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3c5e5e1a-7099-41c3-b8ee-71871d3a5739",
            "sourceColumn": "Query1[Activated]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ffdc557-35a6-498b-a15f-d1c73a8cab88",
            "sourceColumn": "Query1[Sold]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sales_Type_Final",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b1a5de70-ee1a-4991-8c0e-5b70b0692ac0",
            "sourceColumn": "Query1[Sales_Type_Final]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0933d0d3-fa7d-43cf-b973-8d4d9f20e219",
            "sourceColumn": "Query1[Age]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Age_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c0c04008-3d3c-4487-a749-50f52d0ec089",
            "sourceColumn": "Query1[Age_Group]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "day_num_tag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7845893d-fe15-47fd-b05e-b3159328b762",
            "sourceColumn": "Query1[day_num_tag]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Activated_at",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "327c02ce-fbed-4255-9479-b55159e4b359",
            "sourceColumn": "Query1[Activated_at]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e0611511-ec1c-4e40-85a6-01bf0bb1ee60"
                },
                "isDefault": true,
                "relationship": "0e4776e2-9df6-44bc-b11c-8bea94fada94"
              }
            ]
          },
          {
            "name": "Entry_Tickets_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1b51b20b-dfaa-44fd-89c8-7c822dbb2934",
            "sourceColumn": "Query1[Entry_Tickets_Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Wonderpass_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0f640999-1830-444e-b151-720669b98ae3",
            "sourceColumn": "Query1[Wonderpass_Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parking_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "86e59326-f931-47f3-b177-923dd335c82f",
            "sourceColumn": "Query1[Parking_Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ripleys_Combo_Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1d635efe-1185-4efa-9abd-2a744a342449",
            "sourceColumn": "Query1[Ripleys_Combo_Total]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ripleys_Combo_Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2f373cc1-3aae-4b86-8325-9f92d33a11a6",
            "sourceColumn": "Query1[Ripleys_Combo_Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SaleDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "386ef5dc-2c55-4799-885d-ddec9d3ebfbb",
            "sourceColumn": "Query1[SaleDate]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7bc5946e-77c0-415b-b60d-baa43e5eb460"
                },
                "isDefault": true,
                "relationship": "de01d3dd-5dd8-4d88-9095-a0063fb7f9a4"
              }
            ]
          },
          {
            "name": "New Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "397ee94a-b57d-49ee-98e9-2526e1a6d3bd",
            "sourceColumn": "Query1[New Category]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VIP_Utilization_Cabana_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "15ec74bc-6fd9-4e79-ac3a-c53cbb08fd8a",
            "sourceColumn": "Query1[VIP_Utilization_Cabana_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VIP_Utilization_Stunt_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e3f3cb63-93aa-4e1b-83d8-23d00772518b",
            "sourceColumn": "Query1[VIP_Utilization_Stunt_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Stunt Show",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "08804915-8b01-45d1-8fb8-ca2e76ee3f8f",
            "sourceColumn": "Query1[Stunt Show]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Stunt Show Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "827797ce-8ddc-451c-99a9-fe4369343965",
            "sourceColumn": "Query1[Stunt Show Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Cabana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1d3a01fd-42d8-420e-9a96-5428400b2e92",
            "sourceColumn": "Query1[Cabana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Cabana Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8648100b-e5a4-4091-acee-ef6b75567b82",
            "sourceColumn": "Query1[Cabana Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Activation Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "06ae581c-eaba-4fcd-b58f-84fa81ae76e2",
            "sourceColumn": "Query1[Activation Period]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Packs per purchaser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "",
              "Var season =[Season_ID]",
              "Var email_virgin=[Virgin_Email]",
              "return calculate(Count('Distinct packs'[Virgin_Email]),'Distinct packs'[Virgin_Email]=email_virgin,'Distinct packs'[Season_ID]=season,aLL())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b2d68f16-d6d9-430e-a20e-39ff01aa3e3f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Packs per guest",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season =[Season_ID]",
              "Var email=[VW_VIP_ActivationDataset_Email]",
              "return calculate(Count('Distinct packs'[VW_VIP_ActivationDataset_Email]),'Distinct packs'[VW_VIP_ActivationDataset_Email]=email,'Distinct packs'[Season_ID]=season,all())",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "099d0c7e-615f-4a06-a125-9dcc901360aa",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Same purchaser different seasons",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "Var season=Value([Season_ID])",
              "var compared_season=season-1",
              "VAR purchaser_emails_compare=CALCULATETABLE(DISTINCT('Distinct packs'[VW_VIP_ActivationDataset_Mobile])",
              ",Query1[Season_ID]=VALUE(compared_season))",
              "",
              "RETURN",
              "   IF([Virgin_Email] in purchaser_emails_compare,1,0) ",
              ""
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "18371e8d-5731-4fd3-aefa-ab4f5bf913a7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "VW_VIP_ActivationDataset_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9082d19c-c80a-4b03-a7f2-c782f0a011d0",
            "sourceColumn": "Query1[VW_VIP_ActivationDataset_Mobile]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Same guest different seasons query1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4201a4c0-ff2e-4537-bb40-cc576e1ed125",
            "sourceColumn": "Query1[Same guest different seasons query1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Same purchaser different seasons query1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c0d74792-4b6d-4148-8bbf-0adc6f56d689",
            "sourceColumn": "Query1[Same purchaser different seasons query1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Activated_carplate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "400de824-982a-465a-b350-b109b3cd56fa",
            "sourceColumn": "Query1[Activated_carplate]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sold_OnSite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8f109518-055b-4d57-af2b-f14e96c8978c",
            "sourceColumn": "Query1[Sold_OnSite]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sold 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "853b8191-f81b-44e7-8a01-048a0922cc4c",
            "sourceColumn": "Query1[Sold 2]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MirrorMaze_utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b7716849-2cd2-4f58-a37c-bbbc92623c49",
            "sourceColumn": "Query1[MirrorMaze_utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Auditorium Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f9cb92b9-4e4b-4cc0-b663-576ee4d8d3e3",
            "sourceColumn": "Query1[Auditorium Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Wonderpass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "66144358-de0a-4b04-b7fd-1985572bd907",
            "sourceColumn": "Query1[Wonderpass]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "dummy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4259eb4b-e678-4e5d-b9ad-67f08eb92d2d",
            "sourceColumn": "Query1[dummy]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Same guest different seasons S28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8b692d5b-8857-461c-8f49-be7edb8e8a8a",
            "sourceColumn": "Query1[Same guest different seasons S28]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Same purchaser different seasons S28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e3b37b81-1b05-4c5e-90f1-41a178e1dea1",
            "sourceColumn": "Query1[Same purchaser different seasons S28]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Entire pack utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0fa72ba5-de9e-4dd7-bb31-9bca9a77aa95",
            "sourceColumn": "Query1[Entire pack utilization]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Pack Utilization Groups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "38d7b007-d392-457b-a750-410664c5620a",
            "sourceColumn": "Query1[Pack Utilization Groups]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Entry_Tickets_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5eaa6c45-5315-4ca9-aefe-bc5c7b1591d0",
            "sourceColumn": "Query1[Entry_Tickets_Utilization]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WonderPAss_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3c72fcc0-16d7-4efa-89b3-6010dc69aec0",
            "sourceColumn": "Query1[WonderPAss_Utilization]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parking_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8b4505ca-2ccf-49e5-8379-84c2e45800f5",
            "sourceColumn": "Query1[Parking_Utilization]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ripleys_Utilization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1ae95cc7-7809-4a38-b084-17cf893b46b3",
            "sourceColumn": "Query1[Ripleys_Utilization]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VIP_Utilization_Majlis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "92638f33-ee1b-4178-b4ae-97b59f803fae",
            "sourceColumn": "Query1[VIP_Utilization_Majlis]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "VIP_Utilization_Majlis_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c70ca939-7228-45a7-9a2c-637330190e47",
            "sourceColumn": "Query1[VIP_Utilization_Majlis_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Majlis Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7af75aba-7d1b-42b7-8ea1-034d42f380d3",
            "sourceColumn": "Query1[Majlis Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c547ddfc-4b0e-4db2-be7a-d1529b4fe79d",
        "partitions": [
          {
            "name": "Distinct packs-0e371e65-ea04-45b4-b2fb-255f7243670a",
            "mode": "import",
            "source": {
              "expression": "Distinct(Query1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1a28d957-6c5d-4faa-90d9-a455f0254878",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "641afb4c-cb83-4c05-b156-7219bcab6596",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8292c160-1274-42ca-9518-66c4f1b98e76",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3d7bf2cf-09c7-4491-9818-a550641bb46e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "69aff5df-a3c0-487a-ad0d-aea51ced76a7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e8848cfe-da42-44e4-a23f-31e748c6c5ac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "30eff084-83a4-435d-912e-4739765ad3c6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "82a40113-2d85-4456-9b9b-357dc29fc9a3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0078dc6b-8d36-44eb-82f4-3e7e7a068b2a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b0f7871c-b8e3-43b3-825d-24faf0463d94",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "cc710a2a-8f89-4e62-898f-ae691f11feee",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c94d5810-d344-4b61-8a53-bf1cc8186ead",
                "ordinal": 3
              }
            ],
            "lineageTag": "a4f3a130-b624-44fc-9957-9f3240580fb0"
          }
        ],
        "isHidden": true,
        "lineageTag": "0345943a-bab5-443c-a7af-bd0ea85969c1",
        "partitions": [
          {
            "name": "LocalDateTable_1a28d957-6c5d-4faa-90d9-a455f0254878-cb00c4c8-59b6-4d65-a6f1-d1dd32db82a5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Distinct packs'[VW_VIPActivationDataset_DOB])), 1, 1), Date(Year(MAX('Distinct packs'[VW_VIPActivationDataset_DOB])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e0611511-ec1c-4e40-85a6-01bf0bb1ee60",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9e1adb00-4cce-4972-96c3-c9dca51b8a30",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "12b19d0c-64f2-41dd-967e-833a6711f4fa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a5fa0a4-633b-422b-9570-b4a66e4b5eb7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0aa13a0d-15a8-4840-8d5a-589589eee842",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b03591ff-4f01-4d5d-a863-d5a50fb23d59",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cd95ce41-ea61-4c50-81c1-bb7f5c55721b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "40b39d59-02d0-4a39-a416-95907eaedf07",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1b8af9bd-1f77-48c4-8a3b-6d91256848fc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "656e43f4-eeff-4ca0-967c-86538351807d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e2e2a014-92fc-4fd6-bc51-5905061ecad9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8c278191-c663-4efc-91f6-2f1b7c20e818",
                "ordinal": 3
              }
            ],
            "lineageTag": "2b7f731e-c5dd-4d60-ba8d-a7af9580da17"
          }
        ],
        "isHidden": true,
        "lineageTag": "c4425eda-db43-4a98-b81a-ac8c67804077",
        "partitions": [
          {
            "name": "LocalDateTable_e0611511-ec1c-4e40-85a6-01bf0bb1ee60-90ee941c-243d-4bd4-8ed8-ec235130ca8b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Distinct packs'[Activated_at])), 1, 1), Date(Year(MAX('Distinct packs'[Activated_at])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7bc5946e-77c0-415b-b60d-baa43e5eb460",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9b72491a-2886-4745-ba14-0e5c1590fa45",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d1157834-3c6a-4bad-91cf-4b82db28ac76",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c3a162e1-732a-4fda-9bed-37c5d5ddce87",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a87f8187-f7d5-43af-8f64-d4505d8f68fc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cc9286a0-410d-40a8-bb4c-efdb72d04e57",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f9632bc9-8602-4d8b-940f-59b3414f205b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a6a0947-5d51-4393-b1fe-618b91f443d5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3ed3cefe-dd74-4010-9e0d-488fe2cd417e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "06d3ee78-81aa-4842-9509-2036c26d52a7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c2eac32a-44da-4c45-841d-2cc87b4d7e15",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b84e3205-7022-475e-82ca-c18e0d89ca56",
                "ordinal": 3
              }
            ],
            "lineageTag": "5785d981-cba8-4478-925e-38094588ecec"
          }
        ],
        "isHidden": true,
        "lineageTag": "e6d6766f-290e-417f-847a-45e8f25526ce",
        "partitions": [
          {
            "name": "LocalDateTable_7bc5946e-77c0-415b-b60d-baa43e5eb460-61212a23-1313-4376-a76c-1704e8fac75b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Distinct packs'[SaleDate])), 1, 1), Date(Year(MAX('Distinct packs'[SaleDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3b61af33-bad5-4f12-8b5d-d0f12bdd4798",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ff96fbdc-7078-470e-b6bc-fbcce6d62851",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "61bc4b8c-483d-4310-9f92-4231fdc98c50",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "49a2d6e3-d88f-4cec-8f82-4ea52b28e878",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d68e8a45-decf-4abb-bdb9-ed27e2f3cf93",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "15accc27-82a5-490e-a838-0deed891e183",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "076bf204-7e62-4563-8042-eb72780f035e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bffef73f-d128-4fdd-84d0-9f62b1a55371",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e7a53e67-357a-435f-beea-f15745d0cf3f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "856cae48-f286-4317-84db-faed643cbbb8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5110a0b3-abbb-4e0a-b745-2ce9ffa4eeb5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1ad51a62-860f-4845-aca5-5f38c329e5eb",
                "ordinal": 3
              }
            ],
            "lineageTag": "c06a3c73-5a76-4c88-8de2-8127c2cc3e6b"
          }
        ],
        "isHidden": true,
        "lineageTag": "8b45aa97-9ef2-4acf-96b6-85237c916b73",
        "partitions": [
          {
            "name": "LocalDateTable_3b61af33-bad5-4f12-8b5d-d0f12bdd4798-a4825dda-3c5b-41eb-8620-600240671fca",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VIP_Parking'[Op_date])), 1, 1), Date(Year(MAX('VIP_Parking'[Op_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Family Pack",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Season_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca2a6a37-5cf9-41c5-a364-50baa0488636",
            "sourceColumn": "Season_ID",
            "summarizeBy": "count"
          },
          {
            "name": "PackNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e11f2e40-3191-4d8e-ab68-2692f58e6107",
            "sourceColumn": "PackNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12acf626-b4f7-4bcd-95d4-345d24a1e333",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Pack_Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8bd1591e-1336-4ee4-9b6a-b5678fa164ba",
            "sourceColumn": "Pack_Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Activated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c4f3ee1f-38e0-49d0-bee2-1c38014e788d",
            "sourceColumn": "Activated",
            "summarizeBy": "none"
          },
          {
            "name": "Activated_On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a765efc8-4350-475d-9752-2a7ead9f531c",
            "sourceColumn": "Activated_On",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7a13ada1-fa66-4deb-ba1a-4423b16aeac0"
                },
                "isDefault": true,
                "relationship": "c931eec2-de8a-47b3-837c-8bcd85373d13"
              }
            ]
          },
          {
            "name": "Purchaser_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8020ae96-efb0-431c-b18c-6b7d08483ef4",
            "sourceColumn": "Purchaser_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Purchaser_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2b41b21-4d3b-4dcf-aac6-5eeda0065d2b",
            "sourceColumn": "Purchaser_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Purchaser_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78d4b806-b59b-40e2-8878-115bc97ed679",
            "sourceColumn": "Purchaser_Mobile",
            "summarizeBy": "none"
          },
          {
            "name": "Guest_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6aab364-2832-49c7-ae41-ca473111a96c",
            "sourceColumn": "Guest_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Guest_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6739e7f-54cc-4a2b-be88-8ca071b8a75c",
            "sourceColumn": "Guest_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Guest_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "416a63c5-3aa8-4ca4-9291-ec646d57cc6d",
            "sourceColumn": "Guest_Mobile",
            "summarizeBy": "none"
          },
          {
            "name": "Carplate_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72f38d14-3c20-4d7a-9981-9e53071042d3",
            "sourceColumn": "Carplate_1",
            "summarizeBy": "none"
          },
          {
            "name": "Carplate_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "397b28e2-2cd2-40be-b977-90aa10abff4e",
            "sourceColumn": "Carplate_2",
            "summarizeBy": "none"
          },
          {
            "name": "Entry_Ticket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b624bbba-4830-4d1d-8483-d175482d3add",
            "sourceColumn": "Entry_Ticket",
            "summarizeBy": "sum"
          },
          {
            "name": "Entry_Ticket_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68c3059a-dfd3-434e-8c0e-ec076b966608",
            "sourceColumn": "Entry_Ticket_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "WonderPass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6153a1f1-6ede-4cdd-bb78-4abc7603ecbf",
            "sourceColumn": "WonderPass",
            "summarizeBy": "sum"
          },
          {
            "name": "WonderPass_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b8783913-2760-44bb-b865-c26d7ae125f6",
            "sourceColumn": "WonderPass_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Parking_Voucher",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6bb15ded-1ab9-48bb-b621-11fb7e8c1012",
            "sourceColumn": "Parking_Voucher",
            "summarizeBy": "sum"
          },
          {
            "name": "Parking_Voucher_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6175b7df-7095-49d5-89f0-20e133dcfb55",
            "sourceColumn": "Parking_Voucher_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Auditorium",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8b45ca7f-c89d-4152-8891-a5a72e8dd0c9",
            "sourceColumn": "Auditorium",
            "summarizeBy": "sum"
          },
          {
            "name": "Auditorium_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c1f374f-e88b-4ef9-9ce3-29cd94b799c8",
            "sourceColumn": "Auditorium_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "MirrorMaze",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "691517ce-e376-4bdf-993f-fae94c6f18db",
            "sourceColumn": "MirrorMaze",
            "summarizeBy": "sum"
          },
          {
            "name": "MirrorMaze_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "44e06807-3c71-4919-96d5-9298b174d862",
            "sourceColumn": "MirrorMaze_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Sold_OnSite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3dc061f5-ce35-4507-8264-d43e21292210",
            "sourceColumn": "Sold_OnSite",
            "summarizeBy": "none"
          },
          {
            "name": "Cabana_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b42b878e-1fe0-4688-8fe7-1d0ad2e0831b",
            "sourceColumn": "Cabana_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Stunt_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92cc5755-6b40-4e0f-841d-849e9d6fe45a",
            "sourceColumn": "Stunt_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Carwash_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f26b56d-a495-4ae2-ad01-05b79cf38ee9",
            "sourceColumn": "Carwash_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Taxi_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3268df4e-c690-442f-a733-a928dbae6f25",
            "sourceColumn": "Taxi_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Porter_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3d6dace2-9be5-416c-9687-49b233e197e7",
            "sourceColumn": "Porter_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Entry Ticket Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "[Entry_Ticket]-[Entry_Ticket_Remaining]",
            "isDataTypeInferred": true,
            "lineageTag": "e24433eb-c925-4514-9427-5554a0d82dba",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "WonderPass Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "[WonderPass]-[WonderPass_Remaining]",
            "isDataTypeInferred": true,
            "lineageTag": "bc5aca61-65e9-46f3-b719-c401343f1d87",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Parking Voucher Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "[Parking_Voucher]-[Parking_Voucher_Remaining]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f4c4d180-f8ed-4281-9e87-8ca7808e20e6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Season + Pack No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE([Season_ID], [PackNumber])",
            "isDataTypeInferred": true,
            "lineageTag": "22046e9c-d1a9-4ba0-a14b-2749052091b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Majlis_Allowed_Tables",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd5df747-ef92-4b0b-bd6a-b5688b93aeed",
            "sourceColumn": "Majlis_Allowed_Tables",
            "summarizeBy": "sum"
          },
          {
            "name": "Majlis_Remaining_Tables",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c284f800-610d-4885-9dea-f02af6b2fa0e",
            "sourceColumn": "Majlis_Remaining_Tables",
            "summarizeBy": "sum"
          },
          {
            "name": "Adventure_Park_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6d2c614f-3581-4b6f-bfff-21b4cc64e4d4",
            "sourceColumn": "Adventure_Park_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "Mini_Golf_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c0d73ad-ba50-4dec-b0e5-632eebe3149f",
            "sourceColumn": "Mini_Golf_Remaining",
            "summarizeBy": "sum"
          },
          {
            "name": "PurchaserAccountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3ae701c-9fbd-4308-8663-c9c654331367",
            "sourceColumn": "PurchaserAccountId",
            "summarizeBy": "none"
          },
          {
            "name": "GuestAccountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e03987f-e38b-4f21-9a2f-97c78d36b704",
            "sourceColumn": "GuestAccountId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "894e8154-65c2-4d32-a80e-bf3627a356c0",
        "measures": [
          {
            "name": "Entry_Tickets_Utilized_%",
            "expression": "CALCULATE(SUM('Family Pack'[Entry_Ticket_Remaining]))/CALCULATE(SUM( 'Family Pack'[Entry_Ticket]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "81d22fc0-815b-4adc-a236-c59692f8ef8b"
          },
          {
            "name": "Wonder_Pass_Utilized_%",
            "expression": "CALCULATE(SUM('Family Pack'[WonderPass_Remaining]))/CALCULATE(SUM( 'Family Pack'[WonderPass]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e5ad5f8c-ead6-4b8b-9831-b9dc9a5fe2f0"
          },
          {
            "name": "Parking_Utilized_%",
            "expression": "CALCULATE(SUM('Family Pack'[Parking Voucher Utilized]))/CALCULATE(SUM( 'Family Pack'[Parking_Voucher]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f70f6df0-1f78-42c8-a159-d1fafad2bad7"
          }
        ],
        "partitions": [
          {
            "name": "Family Pack-7e58d651-b789-483f-b518-cfb35c27c3c6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\" = Workspaces{[workspaceId=\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"]}[Data],",
                "    #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\" = #\"900de5b0-2f7b-4d94-a465-ee52acdc5d72\"{[dataflowId=\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"]}[Data],",
                "    #\"Family Pack_\" = #\"8be03d99-4c2a-4400-a945-5a9837c7cb86\"{[entity=\"Family Pack\",version=\"\"]}[Data]",
                "in",
                "    #\"Family Pack_\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7a13ada1-fa66-4deb-ba1a-4423b16aeac0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1422ff52-291f-4b5b-8b98-bb582cea81f7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7faedcd3-8d64-4317-a807-60b484439383",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c0b7e94e-6b00-425a-acfd-fdeed808725e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b0a04359-0c8e-4c39-922d-80af912a91c8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7d00ac36-3956-433c-a95a-a7a7ec570874",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2a9792f9-64ec-41a5-bfef-e06389756782",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2c1e3fb4-d7f4-4b75-8093-2ec183196fbb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "92f1c469-a6e0-493b-861f-475331ca6dea",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a8e495f3-9e19-476b-be86-269442e7bdf6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d163c9b3-041a-4e9a-8bae-b7ef3f51bf2a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "74790801-ed45-4a05-b579-03c3aa658829",
                "ordinal": 3
              }
            ],
            "lineageTag": "081655ce-5ee3-4a5a-b162-92463eccc751"
          }
        ],
        "isHidden": true,
        "lineageTag": "6a2d3a80-527d-4e8b-9967-293835a4f112",
        "partitions": [
          {
            "name": "LocalDateTable_7a13ada1-fa66-4deb-ba1a-4423b16aeac0-d7205fbf-78bc-4f7c-b8c0-621d07862598",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Family Pack'[Activated_On])), 1, 1), Date(Year(MAX('Family Pack'[Activated_On])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Distinct family packs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ed36f044fe9142daa0e1ffd88d346ee7"
          }
        ],
        "columns": [
          {
            "name": "Season_ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "96ba20bf-ce97-445c-91cd-654be7037ba0",
            "sourceColumn": "Family Pack[Season_ID]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PackNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "169d5688-e18c-4afb-9177-5bb470a39fe8",
            "sourceColumn": "Family Pack[PackNumber]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2bfd3139-267d-4f9d-a72a-68e0ce65531d",
            "sourceColumn": "Family Pack[Category]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Pack_Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b652150c-1bcb-42b5-822d-e644ce00c758",
            "sourceColumn": "Family Pack[Pack_Price]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Activated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9096726e-1e0f-40a8-bd67-fd51d0cb2946",
            "sourceColumn": "Family Pack[Activated]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Activated_On",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f8061dcd-ea46-42c8-9af1-4fa632898c1d",
            "sourceColumn": "Family Pack[Activated_On]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2eb98c04-eb59-4d06-aa8b-237a6377b0df"
                },
                "isDefault": true,
                "relationship": "31da555a-5de5-4c06-9dee-c0a672c38c97"
              }
            ]
          },
          {
            "name": "Purchaser_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "47d3afee-b97a-411b-87e4-659cfc506c01",
            "sourceColumn": "Family Pack[Purchaser_Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Purchaser_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1c8d6dd3-12dd-4cea-929e-9a58b758132a",
            "sourceColumn": "Family Pack[Purchaser_Email]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Purchaser_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "93110d1c-7dd1-4a74-93a2-a16167895695",
            "sourceColumn": "Family Pack[Purchaser_Mobile]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Guest_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f99af04f-8779-4cc6-92ca-db62830a20c1",
            "sourceColumn": "Family Pack[Guest_Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Guest_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e8a060de-cd35-422c-a650-6374475b4b71",
            "sourceColumn": "Family Pack[Guest_Email]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Guest_Mobile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a3b5ff61-69bd-4257-af7f-f607db1ca5bb",
            "sourceColumn": "Family Pack[Guest_Mobile]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Carplate_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bbd06f70-39ae-4688-b245-3ab7d205a27a",
            "sourceColumn": "Family Pack[Carplate_1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Carplate_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "27f3581d-16d7-4973-9e85-1c626d134832",
            "sourceColumn": "Family Pack[Carplate_2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Entry_Ticket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e78a3af9-8369-4839-b3c9-6589136d23c3",
            "sourceColumn": "Family Pack[Entry_Ticket]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Entry_Ticket_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "71fab680-ba76-4a38-9765-0e9e84678141",
            "sourceColumn": "Family Pack[Entry_Ticket_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WonderPass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "54781f84-c6e2-429b-9616-d105984dccbe",
            "sourceColumn": "Family Pack[WonderPass]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WonderPass_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0f6b6659-4580-4b5f-b238-f64bb5ab4150",
            "sourceColumn": "Family Pack[WonderPass_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parking_Voucher",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7a82ee39-71bb-4d67-b654-a9f752fc65bb",
            "sourceColumn": "Family Pack[Parking_Voucher]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parking_Voucher_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4d230f74-a78b-4e6b-9d78-def293aba1d7",
            "sourceColumn": "Family Pack[Parking_Voucher_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Auditorium",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "823146a4-a21f-4897-a2c6-a2ac204b105a",
            "sourceColumn": "Family Pack[Auditorium]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Auditorium_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3eb4a1c5-0347-4fec-ba33-b66e7de1f9ee",
            "sourceColumn": "Family Pack[Auditorium_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MirrorMaze",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1e84f844-eb19-4831-883e-89394ea7afbc",
            "sourceColumn": "Family Pack[MirrorMaze]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MirrorMaze_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c7ec88a1-714d-45d5-8364-913a9202f388",
            "sourceColumn": "Family Pack[MirrorMaze_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sold_OnSite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dc932508-b4d2-4487-b766-ef27ff1853f4",
            "sourceColumn": "Family Pack[Sold_OnSite]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Cabana_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "dd9b95eb-af5b-45dd-85c6-933c578e2497",
            "sourceColumn": "Family Pack[Cabana_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Stunt_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "96a6ca2e-1e47-4a75-94b1-631d9fd57edf",
            "sourceColumn": "Family Pack[Stunt_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Carwash_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4735ac8a-90ed-443f-bddd-4b53e72bc50c",
            "sourceColumn": "Family Pack[Carwash_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Taxi_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "825e4549-9ec8-4863-b27c-3953a1fd8dbb",
            "sourceColumn": "Family Pack[Taxi_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Porter_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4cabab97-c740-4068-a35a-51f578d3d7f3",
            "sourceColumn": "Family Pack[Porter_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Entry Ticket Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2a747164-b562-4a9c-ad0e-ab946df41eb7",
            "sourceColumn": "Family Pack[Entry Ticket Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WonderPass Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "557592b0-f005-4ba4-b254-c9aec22d3b72",
            "sourceColumn": "Family Pack[WonderPass Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parking Voucher Utilized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "14c9c2fe-89c9-4a20-aabe-651799e94620",
            "sourceColumn": "Family Pack[Parking Voucher Utilized]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Season + Pack No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "68301b66-5761-4dd7-99b6-359efae8df2b",
            "sourceColumn": "Family Pack[Season + Pack No]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Majlis_Allowed_Tables",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1a92e878-840b-4a30-be3e-736c1457f67f",
            "sourceColumn": "Family Pack[Majlis_Allowed_Tables]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Majlis_Remaining_Tables",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6b0f0e23-2d16-494c-a0e8-5fbc3e84adf0",
            "sourceColumn": "Family Pack[Majlis_Remaining_Tables]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Adventure_Park_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d7bfe6d7-20d9-4724-a542-098f4745673e",
            "sourceColumn": "Family Pack[Adventure_Park_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mini_Golf_Remaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7a9ebc3a-d2e6-4f3f-8f7e-af5387612f5e",
            "sourceColumn": "Family Pack[Mini_Golf_Remaining]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PurchaserAccountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "62e6a7d7-5427-4232-95b5-37be68d366a7",
            "sourceColumn": "Family Pack[PurchaserAccountId]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "GuestAccountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f3531657-deae-4f0d-a8a3-c760b7b3ec05",
            "sourceColumn": "Family Pack[GuestAccountId]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "721bae21-4b77-4f3a-9671-70614ffb89df",
        "partitions": [
          {
            "name": "Distinct family packs-e0404c69-4fe4-4640-8c12-c17c9845dd88",
            "mode": "import",
            "source": {
              "expression": "Distinct('Family Pack')",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2eb98c04-eb59-4d06-aa8b-237a6377b0df",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "63376d1a-9825-4c0f-9a22-7da2f4e94aca",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a4f8b927-e3be-4d3c-81cd-c974fcb8b54a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "85b12232-555c-4d80-b33e-6a4bdbe3c8bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "71a70a3f-2732-4103-b588-959f1c5308b9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b7d5504b-a9e5-4e86-a0a6-2ad07ddf3d4d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "767bc60a-a6af-432b-a2b6-ecb9a0c4630d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "45fe347a-950a-463c-97f2-37d9152b89b6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d6bb0c27-3dfa-4176-8aea-aaffe2bfb52a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "1f4d59c9-d9d7-4221-a8fb-fee501d7d48d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d32bc760-8fb2-409e-9022-bebcdaeddc1d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "85e0c76e-88a3-4bcb-acf2-04a9be5c5319",
                "ordinal": 3
              }
            ],
            "lineageTag": "2fbad646-1438-4102-a6f4-1096863a8174"
          }
        ],
        "isHidden": true,
        "lineageTag": "bb466683-5179-4597-a579-1328f3ffa7f4",
        "partitions": [
          {
            "name": "LocalDateTable_2eb98c04-eb59-4d06-aa8b-237a6377b0df-5b73fb0f-c3f2-4cf4-8a17-d70c370288ac",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Distinct family packs'[Activated_On])), 1, 1), Date(Year(MAX('Distinct family packs'[Activated_On])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}